### ISSUE TITLE
After use Update() with many to many i got error : The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.

### ISSUE THREAD

**Issue by iveremeychuk** [SharpRepository/SharpRepository#133]
Its my code.

[Inject]
        public IRepository<AlgoPortfolio> AlgoRepository { get; set; }

[Inject]
        public IRepository<ShareBranch> Sectors { get; set; }

    model.CurrentStep = Steps.Get(model.CurrentStepId);
            if (ModelState.IsValid)
            {
                var entity = AlgoRepository.Get(model.Id);
                var nextStepPosition = model.CurrentStep.Position + 1;
                model.CurrentStep = Steps.Find(q => q.Position == nextStepPosition);
                Mapper.Map(model.RegionAndSectors, entity);
                entity.CurrentStepId = model.CurrentStep.Id;
                entity.Sectors = model.RegionAndSectors.Sectors.Select(q => Sectors.Get(q)).ToList();
                AlgoRepository.Update(entity);
                model.PeriodAndRebalancing = Mapper.Map(entity, new PeriodAndRebalancingViewModel());
                return View("Index", model);
            }

And my error:
Additional information: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.

I understand what my repositories using different context, but i dont understand how to slove it.

Help me please if its possible. Thanks in advance.

**Comment by jtreuting** [comment]
Was there any resolution to this?  I'm going to close since it's so old, just trying to clean up old items at this point.  But if there is a problem that you know of, please respond back and we can reopen.
