### ISSUE TITLE
No CouchDB Repository in NuGet

### ISSUE THREAD

**Issue by synariasol** [SharpRepository/SharpRepository#135]
Hi,

I am currently looking to use CouchDB in a project and stumbled across SharpRepository when trying to find a .NET client for it. However, the CouchDB implementation of SharpRepository doesn't seem to be in NuGet. Is there a reason for this? Could it be added?

Thanks,

Nick.

**Comment by jtreuting** [comment]
The reason there is no NuGet package for it yet is that while it passes all our unit tests, I haven't personally used it in a real application so I'm not sure if it is hardened enough.  The code is available on GitHub if you'd like to use it though.


Jeff

________________________________

**Comment by synariasol** [comment]
Fair enough. I am currently building and including it from the code in GitHub. It just makes the packages easier to manage if they are all referenced using NuGet. 

I going to use it in an application and so shall provide some feedback on its stability at a later date.

**Comment by jtreuting** [comment]
That's great.  I appreciate it.  Hopefully it holds up and if it doesn't just let me know.

________________________________

**Comment by erik5388** [comment]
@jtreuting - Release with alpha flag. Solves everyone issues. Do you have any objections or concerns?

**Comment by jtreuting** [comment]
I'm happy to do that.  Most likely won't be until the beginning of the week, but that makes sense.


________________________________

**Comment by omarpiani** [comment]
Hi @erik5388 , I know is late, but I just released a prerelease version of package

https://www.nuget.org/packages/SharpRepository.CouchDbRepository/1.5.0-prerelease

Remember that is compatible with CouchDb 1.6 
hope you leave some feedback to us.

Regards

**Comment by erik5388** [comment]
Thank you
