### ISSUE TITLE
Support CoreCLR

### ISSUE THREAD

**Issue by eloekset** [SharpRepository/SharpRepository#136]
Create PCLs of the repository implementations that are supported on WinRT/Xamarin. There should be a SharpRepository that can be used to create Universal Apps and also Xamarin apps.

**Comment by eloekset** [comment]
The SharpRepository.Repository Assembly will have to be split up to keep certain platform specific features out of the core Assembly. The Configuration folder seems to have a lot of compile issues in a PCL for WinRT.

Also the .NET Cache Provider in System.Runtime.Caching.dll must be replaced by an implementation for PCL. I found this one: http://ranahossain.blogspot.no/2014/01/cache-provider-for-portable-class.html

**Comment by eloekset** [comment]
I don't think PCL is going to be used much longer now, since [CoreCLR](https://github.com/dotnet/coreclr) will be the future cross platform version of DotNet. It's better to put effort in supporting CoreCLR, and this pull request for MongoDB C# driver can be a great example on what and how to do it: https://github.com/mongodb/mongo-csharp-driver/pull/210 (Source branch at https://github.com/tugberkugurlu/mongo-csharp-driver/tree/dnx)

**Comment by jtreuting** [comment]
This is great, thanks for working on this.

**Comment by eloekset** [comment]
Just a status update. 

It's harder than I expected to port even the core repository, so I started reading a guide on how to port to .NET Core: https://docs.microsoft.com/en-us/dotnet/articles/core/porting/index

I've done step 2 in this branch: https://github.com/eloekset/SharpRepository/tree/AnalyzeForCoreSupport

This is the report after running the analyzer tool:
[ApiPortAnalysis.pdf](https://github.com/SharpRepository/SharpRepository/files/374576/ApiPortAnalysis.pdf)

Turns out that the core library is among the hardest ones to port.

**Comment by eloekset** [comment]
Time for another status update. SharpRepository.Repository and InMemoryRepository projects are now ported and confirmed running in a very simple .NET Core console application.

The following screenshot is taken by running the code in this branch: https://github.com/eloekset/SharpRepository/tree/DotNetCore_ManualRuntimeTests
<img width="960" alt="sharprepository_netcore_1" src="https://cloud.githubusercontent.com/assets/791721/17086009/26439332-51e7-11e6-8604-c1fc31f669e7.png">

I expect to uncover several issues after porting the unit test project, but I'm not able to port that until the Should NuGet package supports NetStandard 1.3, ref this PR https://github.com/erichexter/Should/issues/11. Or I could start by compiling the PR branch and add file references to the assembly until there's an official release of Should.

**Comment by eloekset** [comment]
...and this is the same manual test application running on a Mac.
![sharprepository_netcore_2](https://cloud.githubusercontent.com/assets/791721/17109551/b51c47c8-5298-11e6-906d-11a541848877.png)

**Comment by eloekset** [comment]
A new manual test now running the same Add and GetAll methods on a very early implementation of EfCoreRepository on a Mac. EFCore still lacks a DbSet.Find method, which is heavily used in SharpRepository.EfRepository, so most methods relying on that just throw NotImplementedException while I figure out a way to implement them.
![sharprepository_netcore_3](https://cloud.githubusercontent.com/assets/791721/17747653/06551dfc-64b6-11e6-8708-6960aa5c1c65.png)

Progress of SharpRepository.EfCoreRepository implementation can be tracked in this branch: https://github.com/eloekset/SharpRepository/tree/DotNetCore_EfCoreRepository

**Comment by omarpiani** [comment]
How with that @eloekset ?

**Comment by eloekset** [comment]
I haven't worked on porting to Core for a while. Since MS has decided to go back to csproj files instead of project.json and a lot of the work I've done so far is around changes to config, I think it's better to start all over again once the .NET Standard 2.0 is in Beta or RC. 

The branches I've been working on are full of `#if` blocks that are going to be unnecessary in the future, so instead of introducing a lot of "mess" in the code, it's better to wait and see what can be left out of all that. An example of what I think will be unnecessary in 2.0:

```
#if NET451 
        [ConfigurationProperty("default", IsRequired = false)] 
#endif 
        public string Default 
        { 
#if NET451 
            get { return (string)base["default"]; } 
            set { base["default"] = value; } 
#elif NETSTANDARD 
            get; 
            set; 
#endif 
        } 
```

If anyone has the latest updates on *what, when and how* about .NET Standard 2.0 and VS2017, please post some information in this thread.

**Comment by eloekset** [comment]
@omarpiani I wonder if you can create a `feature/NetStandard` branch in this repo, so I can create a PR from my VS2017 branch against it?

Since it's so much work needed to port this project to .NET Standard 1.6, I think it would be great to have a feature branch that more contributors can collaborate on.

I've tested a build script on AppVeyor against my VS2017 branch. It runs on **Visual Studio 2017** *build worker image* and has *before build script* `dotnet restore SharpRepository.VS2017.DotNetCore.sln` and *after build script* `dotnet pack SharpRepository.VS2017.DotNetCore.sln`. It generates the following build log:
[log.txt](https://github.com/SharpRepository/SharpRepository/files/870398/log.txt)

**Comment by omarpiani** [comment]
tomorrow I will do it for you.

**Comment by omarpiani** [comment]
I created from develop, is right? I think there will be an huge fork.

**Comment by eloekset** [comment]
Thanks @omarpiani! I've sent the PR. Once it's merged, someone with access to the build server should setup a CI script against the new branch that does as described in this comment https://github.com/SharpRepository/SharpRepository/issues/136#issuecomment-289242436 to be able to build the .NET Core solution.

Then we should start porting the tests project to verify functionality is the same as the current full .NET FX version.

**Comment by omarpiani** [comment]
https://ci.appveyor.com/project/jtreuting/sharprepository-iorhw/build/2.0.3 runnig something.. must go now

**Comment by eloekset** [comment]
Nice, looks like the MSBuild task needs `SharpRepository.VS2017.DotNetCore.sln` specified explicitly. No hurry. I'm not working on this tonight anyway.

**Comment by omarpiani** [comment]
I missed something?

**Comment by eloekset** [comment]
In the build log it looks like the `dotnet restore` command completed successfully. Next is `dotnet build` and it fails with the following error message:
<img width="738" alt="2017-04-06_22-39-27" src="https://cloud.githubusercontent.com/assets/791721/24774671/1c6992f6-1b1a-11e7-9f4f-31bcdd6e1b31.png">

**Comment by omarpiani** [comment]
Ok, now AppVeyor compiles! You don't have tests, right?

**Comment by eloekset** [comment]
Great, next up now is converting the tests project. It seems to be a lot of work as well.

**Comment by omarpiani** [comment]
I converted SharpRepository.Test project.. misses Caching tests and some other little ones.
This was the easiest one. But it's a good notice.

**Comment by omarpiani** [comment]
I converted up MongoDbRepository, Samples and Test.Integration projects.

In all tests where EfRepository was needed, I replaced with EfCoreRepository with EfCore using Sqlite in memory.

I noticed @eloekset  removed half RepositoryFactory methods. Atm configuration with app.config, or appsettings.json is a mistery.

Now there is a dozen of tests failing.
Go on!

**Comment by omarpiani** [comment]
Yet another update, main problems are:

- Aggregates not working
- Lazy loading different in EfCore
- Cache not working (or whole test failing)
- app.config (or appsettings.json) unable to test.
- IoC (StructureMap) not working

**Comment by eloekset** [comment]
I've got a branch with 160 passing tests out of 190. I excluded some not able to compile for NetCoreApp. I can see your project has a total of 212 tests, where 139 are passing (when I unload the integrations test project).

It's a bit hard to compare the two projects, because mine is based on the commit where the feature/NetStandard branch was created, and I've not used EfCore.SqLite in-memory. These are the dependencies I've used:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="1.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="Moq" Version="4.7.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="1.1.1" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
    <PackageReference Include="Should" Version="2.0.0-preview-20170321-5" />
    <PackageReference Include="System.Linq.Queryable" Version="4.3.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.0" />
  </ItemGroup>
```

I'm not sure what the best approach is, but maybe EfCore.SqLite in-mem is required for the integration tests. These are the failing tests in my branch:
![2017-06-28_20-26-40](https://user-images.githubusercontent.com/791721/27654332-386b34fa-5c42-11e7-9137-aabcf7acfd47.png)

**Comment by omarpiani** [comment]
Eh.. make a PR so we join the work 👍

**Comment by eloekset** [comment]
Some day I can take a look into how much it takes to rebase my branch onto the latest from this branch. Or I can make a PR of the work-in-progress unit test project I've got. But then we need to make another branch in this repo based on commit https://github.com/SharpRepository/SharpRepository/commit/50f2af216f0259e90ef188e2d96d33e16ebbf8e

**Comment by omarpiani** [comment]
Why create different old branch? I preffer remove divergences as soon is possible.

**Comment by omarpiani** [comment]
Resolved aggregate problems.

MemoryCache is a big problem, MemoryCache.Default is removed, and every time Repository is instantiated, memorycache is instantiated as well. At the moment seems impossibile to save a variable Globally in .NET Core. Let me know if you have an hint for that.

**Comment by omarpiani** [comment]
Obvious solution is passing MemoryCache instance as required parameter.

Now only 28 test not running

**Comment by omarpiani** [comment]
Is better mantaining the lower standard version is possible in order to get the larger compatibility, for now I downgraded to 1.5

**Comment by eloekset** [comment]
Watch this: https://channel9.msdn.com/Blogs/dotnet/NET-Core-20-Released
Now we know the answer of my comment from Jan 1st. We don't strictly need to do anything to this library. It can be used for .NET Core 2.0 apps as is.

Once the build server is upgraded to support .NET Core 2.0 and the VS2017 update 15.3 builds, we can convert project files to .NET Standard libraries and make them output both netstandard2.0 and net35, net452 etc to make use of the new tooling. There should be no need for any code changes.

I bet .NET Core 1.0 and 1.1 will die pretty soon now. So all the work we've done so far, will probably never be asked for anymore. But we can keep the branch for a while in case I'm wrong. 😅

**Comment by omarpiani** [comment]
Hi! I take a look on that. 
The .NET Standard 2.0 is awsome, this makes .NET Core 2.0 the better choice if you want to start a new project. But on an existing projects, this upgrade forces to upgrade the user codebase.

I'm pretty sure that .NET Core 1.1 will die soon, but we must take care about old 4.x apps, that can reference .NET Standard 1.x libraries

**Comment by omarpiani** [comment]
In #182 I'm testing multi targeting .NET Standard 1.5 and 2.0.

**Comment by omarpiani** [comment]
released beta version of packages compatible with .NET Framework 4.5.1, .NET Standard 1.3 and 2.0 and new EfCoreRepository 🥇
