### ISSUE TITLE
Upgrade to StructureMap 4.x

### ISSUE THREAD

**Issue by fiorebat** [SharpRepository/SharpRepository#144]
There is a new version of StructureMap since March 2014.. Current IoC integration isn't supporting that version, I watch your source, upgrade is not easy.

After we end with PR https://github.com/SharpRepository/SharpRepository/pull/143 I will be glad to help you with that upgrade

Regards

**Comment by fiorebat** [comment]
As  promised I did PR #145 seems working like a sharm

**Comment by jtreuting** [comment]
Merged in today (finally, sorry).  I will work on updating the NuGet pacakge shortly.

**Comment by fiorebat** [comment]
I'm waiting this Nuget package more intensely than Star Wars VII :+1:

**Comment by jtreuting** [comment]
Okay, there are 2 new NuGet packages.  The new SharpRepository.Ioc.StructurMap and the new main SharpRepository.Repository with a couple small improvements.

**Comment by fiorebat** [comment]
Seems perfect, in next days I will try better.

Good Job!
