### ISSUE TITLE
How to include only some child properties?

### ISSUE THREAD

**Issue by cakriwut** [SharpRepository/SharpRepository#146]
Sorry if this question sounds stupid, but I can't find the example of using FetchStrategy.

Imagine I have entities like this:
```c#
public class MainEntity {
     public int Id {get;set;}
     public IEnumerable<ChildEntity> Children {get;set;}
}

public class ChildEntity {
    public int Id {get;set;}
    public string ShowWithParent {get;set;}
    public string DontShowWithParent {get;set;}
}
```

I am looking the way to be able to query MainEntity that will eagerly load ChildEntity.ShowWithParent but exclude ChildEntity.DontShowWithParent.

Thanks for helping me.

**Comment by jtreuting** [comment]
Are you using Entity Framework?  If so, how would you do it there?


If you include Children in the eager loading, then the SQL produced by EF includes all the columns and you would need to limit them by doing a Select() that only includes what you want.


Jeff

________________________________

**Comment by fiorebat** [comment]
I'm feeling too that in your question there's something wrong. You can eager-lazy loading only relations between 2 entities (joins) not a single string property, in my opinion.

I write few example lines of code about eager  loading with SharpRepository in this question 

https://github.com/SharpRepository/SharpRepository/issues/99

Still waiting Jeff :) :+1: 

Regarding

**Comment by cakriwut** [comment]
Hi @jtreuting , I am using Entity Framework. 
Basically I need to selectively eager load Children fields. Some of the Children field in my case contains binary , which I don't want to include during GetAll.

**Comment by cakriwut** [comment]
Hi @fiorebat .
Using your example, I can make a case like this?
- Author has many Books
- A book has publishdate and file binary

And the resolution code is like this?

var _authorList = authors.GetAll(includePaths: a => a.Book.Publishdate)

**Comment by fiorebat** [comment]
You have a little bit of confusion:
First of all in Get/GetAll methods includePaths parameter is available only in a development branch.

I'll write you an example working in current stable version.

Using this models:
```
class Book
{
    public int id { get; set; }
    public string title { get; set; }
    public Author author { get; set; }
    public BinaryBook binaryBook { get; set; }
    public DateTime publishDate { get; set; }
}

class Author
{
    public int id { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string securityToken { get; set; }
}

class BinaryBook
{
    public int id { get; set; }
    public string mimeType { get; set; }
    public int length { get; set; }
    public string fileName { get; set; }
    public byte[] data { get; set; }
}
```

If you have the needing to show a list of books with their authors, you need to get all books, with something like
`SELECT * FROM Books b INNER JOIN Authors a ON b.AuthorId = a.Id`

and you obtain that with
```
var specs = new Specification<Book>();
specs.FetchStrategy.Include(b => b.Author);
var books = repo.FindAll(specs);
```

Without that EF will produce a query for every to Author for every single Book. Not really performant. With a million of records you will feel the difference

When you need to download the file just

```
var book = books.Get(id.Value);
var data = book.binaryBook.Data;

```

it creates the query:

`SELECT * FROM Books WHERE id = ?`

And at runtime, with the default lazy loading beaviour, when you acces binaryBook he will run the query

`SELECT * FROM BinaryData WHERE BookId = ?`

Time is constant for this. Is near to useless (just a millisecond) do eager loading for binaryBook.

For publishDate there's no sense in terms of performance to be excluded in query (ok, if you have 1500 columns we can talk about)

Can be interesting cut off columns for security reasons, for example Author's securityToken, but in this case I suggest to use a proper library to manage mapping from Model to ViewModel like the wonderful  http://automapper.org/

After that consulence a paypal donation will be appreciated!

Just kidding, good work

**Comment by cakriwut** [comment]
:+1:  thanks @fiorebat  , I will try that and I do use SharpRepository with  http://automapper.org  and http://autofac.org

**Comment by fiorebat** [comment]
I can help you with http://structuremap.github.io/, never used autofac :)

You are wellcome
