### ISSUE TITLE
ODataRepository

### ISSUE THREAD

**Issue by xplatsolutions** [SharpRepository/SharpRepository#148]
I had this idea of an ODataRepository and bumped on your blog post. It seems that you almost made it complete but never included in your SharpRepository project. Any problems you have found and stopped you from moving forward with that?

**Comment by fiorebat** [comment]
In last years Jeff is busy, but he accepts PR, if you have time try to merge this branch https://github.com/SharpRepository/SharpRepository/tree/odata with master

Hope you will help this project! Thanks!

**Comment by jtreuting** [comment]
I honestly don't remember how far I got with it.  I think the basics were covered as it was more of an experiment/exercise at that point in how to write a LINQ provider.

**Comment by xplatsolutions** [comment]
Thank yo for the quick response @fiorebat and @jtreuting.

I think most of the implementation needed is there, I will clone and check it out locally.
