### ISSUE TITLE
EfRepository dbcontext return null

### ISSUE THREAD

**Issue by muhammetsahin** [SharpRepository/SharpRepository#149]
Hi,

I have a problem with efrepository. I have two option to create new repository.

`  public class ServisHasarRepository : EfRepository<DE.ServisHasar, int>, IServisHasarRepository
    {
        private readonly IRepository<DE.ServisHasar, int> _servisHasarRepository;

        public ServisHasarRepository(HayPortalEntities hayPortalEntities,
            ICachingStrategy<DE.ServisHasar, int> cachingStrategy = null) : base(hayPortalEntities, cachingStrategy)
        {
            this.CachingEnabled = false;

            _servisHasarRepository =new EfRepository<DE.ServisHasar, int>(hayPortalEntities,null);
        }

        public DE.ServisHasar GetServisHasarById(long id)
        {

            var specs = new Specification<DE.ServisHasar>(s => s.Id==id);
            specs.FetchStrategy.Include(b => b.Araclar);

            var config = new SharpRepositoryConfiguration();
       
            var result= _servisHasarRepository.FindAll(specs);
            var result2 = GetAll().Take(10);

            return result.FirstOrDefault();
        }

    }`

` public interface IServisHasarRepository : IRepository<DE.ServisHasar, int>
    {
        DE.ServisHasar GetServisHasarById(long id);
    }`

`  [TestMethod]
        public  void get_servis_hasar_by_id()
        {
            var dbContext=new HayPortalEntities();

            var mock = new Mock<ServisHasarRepository>(dbContext, null);
            mock.As<IServisHasarRepository>().Setup(framework => framework.GetServisHasarById(It.IsAny<long>()));

            var lovable = mock.Object;
            var result =  lovable.GetServisHasarById(10024);

            mock.As<IServisHasarRepository>().Verify(framework => framework.GetServisHasarById(It.IsAny<long>()), Times.AtMostOnce());

        }`

My problem is when i use this.GetAll or FindAll the method returning null but i try with _servisHasarRepository.GetAll or FindAll the method returning list or entry etc.

Where is the problem?

**Comment by fiorebat** [comment]
Let me understand, if you replace 
var result= _servisHasarRepository.FindAll(specs);
with 
var result= this.FindAll(specs);
result is null?

HayPortalEntities is an extension of DbContext?

According to http://fairwaytech.com/2013/02/sharprepository-configuration/ in "CUSTOM REPOSITORIES" 

you only need

```
        public User GetServisHasarById()
        {
               var specs = new Specification<DE.ServisHasar>();
               specs.FetchStrategy.Include(b => b.Araclar);
                return authorsRepo.Find(specs, x => x.Id == id);
        }
```

 var config = new SharpRepositoryConfiguration(); this row seems unused.

Try a simpler test, using default DbContext and access and use a real LocalDb, I feel a sensation that your test is not mocked correctly

**Comment by muhammetsahin** [comment]
yes definitely right.

and yes HayPortalEntities is my DbContext

ok. i will try  simple sample
