### ISSUE TITLE
Redis cache implementation key not found exception

### ISSUE THREAD

**Issue by muhammetsahin** [SharpRepository/SharpRepository#150]
Hi there,

I added redis cache implementation to my project. But i think it has a bug with that. 
I've got an error like.

'System.Collections.Generic.KeyNotFoundException' 

"Given the key was not in the dictionary."

![image](https://cloud.githubusercontent.com/assets/2045788/14552340/1010d408-02e6-11e6-83d6-083cd96728eb.png)

**Comment by fiorebat** [comment]
Are you sure is an Redis related problem?
with  "none" as strategy and "inmemory" as provider you really don't have the problem?

it's strange you are using container.RegisterSharpRepository(config);
and than you register the repository for IRepository<ServisHassar>

**Comment by muhammetsahin** [comment]
I've changed the code. But i cant solved how should i code register using simple injector.

The configuration is invalid. Creating the instance for type IServisHasarRepository failed. There are no repositories configured


`   var config = new SharpRepositoryConfiguration();
      //var cachingStrategy = new StandardCachingStrategy<Domain.Models.ServisHasar, long>
      //{
      //  CachingProvider = new RedisCachingProvider("172.17.4.181", 6379, false),
      //  CachePrefix = "HP",
      //  GenerationalCachingEnabled = true,
      //};
      config.AddRepository(new EfRepositoryConfiguration("ef", "HayPortalEntities", typeof(TrackerContext), "standard", "inmemory")); // EF repository named ef5 using the DefaultConnection connection string
      config.AddRepository(new InMemoryRepositoryConfiguration("inmemory", "standard", "memcached")); // InMemoryRepository named default using the none CachingStrategy

      config.AddCachingStrategy(new TimeoutCachingStrategyConfiguration("timeout", 30)); // Timeout strategy named timeout with 30 second cache time
      config.AddCachingStrategy(new StandardCachingStrategyConfiguration("standard")); // Standard strategy named standard
      config.AddCachingStrategy(new NoCachingStrategyConfiguration("none")); // No caching named none
      
      config.AddCachingProvider(new MemCachedCachingProviderConfiguration("memcached", "memcached"));  // memcached provider named memcached and using the memcached section in config file
      config.AddCachingProvider(new InMemoryCachingProviderConfiguration("inmemory")); // InMemory provider name inmemory
      config.AddCachingProvider(new RedisCachingProviderConfiguration("redisProvider")
      {
        Host = "172.17.4.181",
        Port = 6379,
        Ssl = false,
        
      }); // Redis provider name redisProvider

      config.DefaultRepository = "ef";
      config.DefaultCachingStrategy = "standard";
      config.DefaultCachingProvider = "inmemory";//"inmemory";
    

      //var config1 = new EfRepositoryConfiguration("ef", "HayPortalEntities", typeof(TrackerContext));
      //var factory = new EfConfigRepositoryFactory(config1);
      //var repos1 = factory.GetInstance<Domain.Models.ServisHasar, long>();

      container.Register<IRepository<Domain.Models.ServisHasar, long>>(() => RepositoryFactory.GetInstance<Domain.Models.ServisHasar, long>(config),Lifestyle.Singleton);
      container.RegisterSingleton<IAraclarRepository>(new AraclarRepository());
      container.Register<IServisHasarRepository, ServisHasarRepository>();

      //container.Register<IServisHasarRepository>(() => new ServisHasarRepository(new HayPortalEntities(), cachingStrategy), Lifestyle.Singleton);

      container.RegisterSharpRepository(config);

      RepositoryDependencyResolver.SetDependencyResolver(new SimpleInjectorDependencyResolver(container));`

**Comment by fiorebat** [comment]
ok, but, cutting off all your SimpleInjector configuration,  new ServisHasarRepository(new HayPortalEntities(), cachingStrategy), Lifestyle.Singleton); is working?

when it's working try the RepositoryFactory

 RepositoryFactory.GetInstance<Domain.Models.ServisHasar, long>(config),Lifestyle.Singleton)

then try put hands on SimpleInjector...

**Comment by omarpiani** [comment]
If problem urges again write something and I will reopen
