### ISSUE TITLE
RavenDbRepositoryBase shouldn't call Dispose on DocumentStore

### ISSUE THREAD

**Issue by GregRar** [SharpRepository/SharpRepository#152]
Hi

According to documentation DocumentStore object should be created once per app (singleton).
I initialize DocumentStore in DocumentStoreHolder like in official documentation.

My issue is that when I use sharp repository within "using" statement (just to close session after I finish) it also dispose of my DocumentStore. 

I believe that only Session.Dispose() should be called.

Performance wise, if DocumentStore is not passed but it's created by RavenDbRepositoryBase that probably should be singleton as well. The documentation states it's initialization is costly.

https://ravendb.net/docs/article-page/3.0/csharp/client-api/creating-document-store

Regards
Greg

**Comment by omarpiani** [comment]
removed DocumentStore dispose 👍
