### ISSUE TITLE
RavenDbRepository method Get should call session.Load<T>(id)

### ISSUE THREAD

**Issue by GregRar** [SharpRepository/SharpRepository#153]
Hi

I've found that Get method on RavenDbRepository uses session.Query by property name Id instead of doing session.Load<T>(id). This has huge performance implication because RavenDB indexes are eventually consistent. When calling Query right after Add then data might be not yet available. 

There are few ways to force Raven to wait for non-stale indexes like setting ConsistencyOptions.AlwaysWaitForNonStaleResultsAsOfLastWrite but this have huge performance issues.

When calling session.Load<T>(id) data is always consistent and it's very fast.

Similar issue reference as example:
http://stackoverflow.com/questions/11867463/ravendb-why-when-querying-docs-by-id-load-returns-value-and-query-does

Regards
Greg

**Comment by fiorebat** [comment]
It seems a good and safe improvement, I hope that @jtreuting will accept a PR on that.

Remember that there is a https://github.com/SharpRepository/SharpRepository/tree/develop/SharpRepository.Benchmarks.Configuration where you can write a good test :+1:

**Comment by jtreuting** [comment]
Yes that does seem like a logical change and I would happily accept a PR!

**Comment by omarpiani** [comment]
https://ravendb.net/docs/article-page/3.5/csharp/client-api/configuration/conventions/querying#defaultqueryingconsistency

AlwaysWaitForNonStaleResultsAsOfLastWrite is deprecated.

**Comment by omarpiani** [comment]
Get method uses GetQuery that uses Session.Load<T>(), Session.Query<T> is used in FindAll and GetAll. 
There something wrong with your question? 
If you are interested in this I will reopen this immediately.
