### ISSUE TITLE
SharpRepository not loading Include Paths when using QueryOptions

### ISSUE THREAD

**Issue by thirsh** [SharpRepository/SharpRepository#156]
When using GetAll with QueryOptions and IncludePaths arguments, the include path properties are not loading. Using GetAll without QueryOptions will load the include path properties. I am using version 1.4.7.2 with EntityFramework6 and Sql Server.

My entities for clarity:

```
public class Widget
{
    public int Id { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Doodad> Doodads { get; set; }
}

public class Doodad
{
    public int Id { get; set; }
    public int WidgetId { get; set; }
    public virtual Widget Widget { get; set; }
    public string Name { get; set; }
}
```

The repository is injected as such:

`IRepository<Widget, int> widgetRepo`
And here is the usage:

```
var pagingOptions = new PagingOptions<Widget>(pageNumber, pageSize, "Id");

var widgets = _widgetRepo.GetAll(pagingOptions, "Doodads");  //Doodads will be null

var widgets2 = _widgetRepo.GetAll(pagingOptions, x => x.Doodads);  //Doodads will also be null

//now if I invoke GetAll without query options, Doodads will be loaded on the widgets that I already got
_widgetRepo.GetAll("Doodads");  //Doodads on widgets and widgets2 will now be loaded
```

**Comment by omarpiani** [comment]
Can you run this tests?

1)  GetAll and strategy
```
var strategy = new GenericFetchStrategy<Widget>();
strategy.Include(x => x.Doodads);
var widgets = _widgetRepo.GetAll(pagingOptions, strategy);
```

2) FindAll and specification
```
var specs = new Specification<Widget>();
specs.FetchStrategy.Include(x => x.Doodads);
var widgets = _widgetRepo.FindAll(specs, pagingOptions);
```

Regards

**Comment by thirsh** [comment]
The first test (GetAll and strategy) did not populate Doodads.

The second test (FindAll and specification) works - the Doodads are populated.

**Comment by omarpiani** [comment]
Thanks! Can you go ahead with second way I hope until someone fixes the bug!

So it was an older bug @jtreuting ?

**Comment by thirsh** [comment]
Yes, I can go ahead with that.  Thanks so much!  BTW, fantastic library.

**Comment by omarpiani** [comment]
Found bug in https://github.com/SharpRepository/SharpRepository/commit/f11ed9e6ed73cd61eb144e1dd620903da16136bf#diff-56829257fe4307266fae658a4117a0b2 

Solution moved to ComposedKeyRepository too.. test it!
