### ISSUE TITLE
Activating AppVeyor MongoDB

### ISSUE THREAD

**Issue by omarpiani** [SharpRepository/SharpRepository#166]
@jtreuting !

Only activating MongoDB service on appveyor the Mongo Unit Tests will no longer be skipped!

Regards!

**Comment by omarpiani** [comment]
need access to appveyor!

**Comment by jtreuting** [comment]
I don't see how to add someone.  When you login using your GitHub account do you have access since you are a contributor?

**Comment by omarpiani** [comment]
Seems inside https://ci.appveyor.com/team, you put me (omar.piani@gmail.com) in a group, then you set the permissions to the group in project

**Comment by omarpiani** [comment]
Maybe only GitHub team members ( https://github.com/orgs/SharpRepository/people ) are automatically authorized

**Comment by jtreuting** [comment]
Just added, let me know if that works.

**Comment by omarpiani** [comment]
Works! It was difficut, a relogin was needed.
