### ISSUE TITLE
NuGets updates

### ISSUE THREAD

**Issue by omarpiani** [SharpRepository/SharpRepository#169]
It's good to have some new prerelease nuget package of actual develop branch to test if new updates are working.

How we do that @jtreuting ?

**Comment by omarpiani** [comment]
Yuhu 😸 

1.4.8 is a good version now... is a good point to release a new nuget version.

**Comment by omarpiani** [comment]
@jtreuting !!!

**Comment by jtreuting** [comment]
What do you need exactly?  Sorry not sure I'm following.

**Comment by omarpiani** [comment]
**Nugets**
That you realease a 1.5.0-prerelease version of all nuget packages
_or_
Gimmi the nuget rights to do that

**Project Hooks**
AppVeyor can automatize nuget and github releases, but I need to be member of the staff of group SharpRerpository to manage github keys.

**Comment by jtreuting** [comment]
I'm going to email and get you what is necessary.

**Comment by omarpiani** [comment]
Great! On monday I put hands on this.

**Comment by omarpiani** [comment]
T_T be member of team did't enable settings menu.. i suppose is only for admins. Btw is not urgent

**Comment by omarpiani** [comment]
Thank you!
At the moment I stay without automatisms :)

I'm releasing new versions of packages!

 I'm removing nuspec files.
With recent nuget versions i use
`nuget pack path/to/project.csprj` 
that will use project.json informations.
