### ISSUE TITLE
NullReferenceException RepositoryBase.GetPrimaryKeyPropertyInfo

### ISSUE THREAD

**Issue by efalsken** [SharpRepository/SharpRepository#170]
I have a case where if our application, during initialization, brings up multiple repositories, (potentially for the same type) and tries to insert an object into each of them. Both repositories will look for the `PrimaryKeyPropertyInfo` and (looking at the code) tries to save the key information to the `InternalCache.PrimaryKeyMapping` dictionary. This Dictionary is not thread safe and throws with a `NullReferenceException` during the `.Add` operation. I'd suggest replacing this `Dictionary` with a `ConcurrentDictionary` at the very least, as it is a Static and can be used in many places around the system. I'd also recommend adding a lock statement and double-lock around the body of `RepositoryBase<T,TKey>.GetPrimaryKeyPropertyInfo()` to avoid potential threading collisions since you're manipulating a static `Dictionary`.

In this case, because I was using the `EfRepositoryBase`, I was able to add `[Key]` to my primary key (in addition to `[RepositoryPrimaryKey]` and avoid the whole issue in `RepositoryBase`.

**Comment by jtreuting** [comment]
That makes sense, good catch.  Are you able to submit a PR for this?

**Comment by efalsken** [comment]
Not at this time. I'm just not set up for it right now.

**Comment by omarpiani** [comment]
InternalCache.PrimaryKeyMapping was resolved in #179 request.

> adding a lock statement and double-lock around the body of RepositoryBase<T,TKey>.GetPrimaryKeyPropertyInfo() to avoid potential threading collisions since you're manipulating a static Dictionary.

Not managed atm.

**Comment by tynorton** [comment]
This case seems resolved.

**Comment by omarpiani** [comment]
Good, I close this, in case we can reopen it
