### ISSUE TITLE
Upgrade to .NET 4.5 in order to upgrade RavenDB to 3.5

### ISSUE THREAD

**Issue by omarpiani** [SharpRepository/SharpRepository#171]
In order to resolve slowness on testing caused by RavenDB embedded, in develop branch with VS2015.

I'm testing that locally, but why not publish that?

Also upgrade was needed in #72 , and there you talk about.
What repercussions upgrading to 4.5 you are afraid?

**Comment by jtreuting** [comment]
At this point I don't see any issues with upgrading and making .NET 4.5 required.  It's been around long enough where I don't feel we need to support older versions moving forwarded.  It was a few years ago when we discussed it before so it wasn't as clear cut in my mind at that point.

**Comment by omarpiani** [comment]
Develop branch is 4.5.2
