### ISSUE TITLE
Applying Specification<> conditions will discard existing FetchStrategy values

### ISSUE THREAD

**Issue by tynorton** [SharpRepository/SharpRepository#172]
Hello, we've uncovered some undesirable behavior when using SharpRepository in our application.

It seems any time you apply a condition to a `Specification<>`, it will instantiate a whole new one, and throw away any property data (i.e. FetchStrategy)

Example:

Bad Code:
```
var findAllBySpec = new Specification<SupplyOrder>(obj => obj.Part.Location.DataSetId == dataSetId)
    .And(obj => obj.Status == status);

findAllBySpec.FetchStrategy = new GenericFetchStrategy<SupplyOrder>();
findAllBySpec.FetchStrategy
    .Include(obj => obj.Part)
    .Include(obj => obj.Part.BufferProfile)
    .Include(obj => obj.Part.Location);
    
// NOTE: This line will erase my FetchStrategy from above
if (null != specification)
{
    findAllBySpec = findAllBySpec.And(specification);
}
```

Working Code:
```
var findAllBySpec = new Specification<SupplyOrder>(obj => obj.Part.Location.DataSetId == dataSetId)
    .And(obj => obj.Status == status);
            
if (null != specification)
{
    findAllBySpec = findAllBySpec.And(specification);
}

// Fetch strategy must be applied after all conditions, or it will be discarded
findAllBySpec.FetchStrategy = new GenericFetchStrategy<SupplyOrder>();
findAllBySpec.FetchStrategy
    .Include(obj => obj.Part)
    .Include(obj => obj.Part.BufferProfile)
    .Include(obj => obj.Part.Location);

return this.FindAll(findAllBySpec)
    .ToList();
```

Cheers,
Ty

**Comment by omarpiani** [comment]
I think is modify Predicate after Strategy... condition can't be a problem.

**Comment by omarpiani** [comment]
I added a solution in last commit  https://github.com/SharpRepository/SharpRepository/commit/f11ed9e6ed73cd61eb144e1dd620903da16136bf#diff-219fedda1a4a5bb15bb9bb8e1cf30417


In old version` findAllBySpec = findAllBySpec.And(specification);` removes all FetchStrategies.
New version creates a new GenericFetchStrategy with the union of current IncludeStrategies of the 2 merged strategies.

The problem will appear if you have custom FetchStrategies.. strategies will be replaced with an GenericFetchStrategy.

Better solution is surelly use the `And `with an expression, this will keep current specifications.
