### ISSUE TITLE
Opt out of GeneratePrimaryKey for int keys

### ISSUE THREAD

**Issue by eloekset** [SharpRepository/SharpRepository#173]
I've got an InMemoryRepository into which I'm adding an entity with key property of type int, and I want the value to be 0. InMemoryRepository automatically generates a value of 1.

The same thing would happen if I wanted an entity with Guid.Empty as key.

Also EfRepository would do the same for keys of type Guid.

I think these two repositories should have a configuration property to opt out of automatic key generation ```public bool GenerateKeyOnAdd { get; set; }```.

**Comment by omarpiani** [comment]
I added some test for Int Key. 

As supposed, **GenerateKeyOnAdd setted on true does NOT affect Ef over SQL Server where Key is an Identity column**, new value was generated from SQL Server and returned to object.

InMemory works as requested. GenerateKeyOnAdd set to false will add 0 to Key value, btw I noticed #180 issue, [Key] attribute has ignored
