### ISSUE TITLE
Upgrade MongoDBRepository to support MongoCSharpDriver 2.4.3

### ISSUE THREAD

**Issue by kayhustle** [SharpRepository/SharpRepository#177]
Can you please upgrade this repository to support the latest version of the Mongo C# driver?  The project would also have to be upgraded to .net 4.5.2

**Comment by omarpiani** [comment]
Hi.
Develop branch is already in .NET 4.5.2. 
In next days I try to upgrade mongo driver, if there are no problems, it will be ready soon.
The problem can be release a nuget package. 
Are you able to use a (self)compiled version?

**Comment by omarpiani** [comment]
Upgraded to 4.5.2 and MongoCSharpDriver 2.4.3.
All tests are running locally, but in CI AppVeyor, some tests are not running.

Btw MongoCSharpDriver is marked legacy and MongoDB.Driver is suggested.
May be a good thing upgrade tu latest suggested version.

**Comment by kayhustle** [comment]
I appreciate your quick response.  I downloaded the source and it still says 1.11.0.
https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.MongoDbRepository/packages.config
I do see the upgrade to 4.5.2 though.  Am I looking at the wrong place?
Thanks

**Comment by omarpiani** [comment]
Only god knows what I did 😞

**Comment by omarpiani** [comment]
MongoCSharpDriver 2.4.3 installs MongoDB.Driver, so MongoCSharpDriver can be removed. I take some time to clean up the Repository

**Comment by omarpiani** [comment]
Take a look!

**Comment by kayhustle** [comment]
This version works!  Good work.  Thanks so much!

**Comment by omarpiani** [comment]
I corrected some bugs. Let me know if https://github.com/SharpRepository/SharpRepository/releases/tag/1.4.8 binaries are working

**Comment by kayhustle** [comment]
Looks good, been using with good results.  Thanks!
