### ISSUE TITLE
InternalCache.PrimaryKeyMapping is not thread safe

### ISSUE THREAD

**Issue by tynorton** [SharpRepository/SharpRepository#179]
Ran into this while running a bunch of our unit tests in parallel. Seems like swapping out for a `ConcurrentDictionary<>` should be sufficient.

**Comment by omarpiani** [comment]
I tested in feature/NetStandard core with no issues, later I will test in develop branch.

**Comment by omarpiani** [comment]
Pushed to develop, will be inserted in next nuget release
