### ISSUE TITLE
The usage of PagingOption

### ISSUE THREAD

**Issue by yyljwyy** [SharpRepository/SharpRepository#181]
I have the code like these:

       PagingOptions<CA> pagingOptions = null;
            int iSortCount = int.Parse(nvcQueryStrings["iSortingCols"]);
            for (int iSortIndex = 0; iSortIndex < iSortCount; iSortIndex++)
            {
                int iColIndex = int.Parse(nvcQueryStrings["iSortCol_" + iSortIndex]);
                string sOrder = nvcQueryStrings["mDataProp_" + iColIndex];
                bool bDesc = nvcQueryStrings["sSortDir_" + iSortIndex] == "desc";
                if (iSortIndex == 0)
                    pagingOptions = new PagingOptions<CA>(request.iDisplayStart / request.iDisplayLength + 1, request.iDisplayLength, sOrder, bDesc);
                else
                    pagingOptions.ThenSortBy(sOrder, bDesc);
            }
            DbContextExtensions.SetTimeOut(this.context);
            var CAs= repository.FindAll(spec, pagingOptions);

Now I just want to page the result and don't want to sort it. It is because the query will be very slow when set the parameter sOrder.
How should I do for the code to remove the sort function? Thank you!

**Comment by omarpiani** [comment]
are you using EntityFramework? If yes
```
var query = repository.FindAll(spec)
var pagedQuery = pagingOptions.Apply(query);
```

**Comment by yyljwyy** [comment]
I do think it become more slow because we load all the data from DB and then page it.
The total amount is 1000000+, and I aborted the code after 1 min.
Would you please help to give some other solution for this problem? Thank you!

**Comment by omarpiani** [comment]
but.. are you able to run a good query directly in EF? try sql profiler to debug that query..

**Comment by omarpiani** [comment]
https://stackoverflow.com/questions/34531818/entity-framerowk-skip-take-is-very-slow-when-number-to-skip-is-big

seems a SQL/Entity Framework problem.

try if "OFFSET x ROWS FETCH NEXT y ROWS ONLY" in sql is fast, if SELECT TOP solution is better, verify if there are a index in the default ordering column.

**Comment by yyljwyy** [comment]
I just adjust the SQL server and create NONCLUSTERERED Index on main table.
It seems there are 70% sources on count sql. Is there any way to adjust it?
Thank you!

**Comment by omarpiani** [comment]
which count? are you talking about sql? difficult to analyze without database in my hands. SQL Server has a wonderfull query analyzer, https://dba.stackexchange.com/ is a better place for your problems.
