### ISSUE TITLE
Join and ToListAsync Repositories throws Exception in EfCoreRepository

### ISSUE THREAD

**Issue by zabihy** [SharpRepository/SharpRepository#183]
When I Join Repositories and make them awaitable by ToListAsync, the following exception throws:
: System.InvalidOperationException : The source IQueryable doesn't implement IAsyncEnumerable<Arman.Letter.Service.AccountIdEmailAddress>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations

**Comment by omarpiani** [comment]
whoa.. can you write a simple unit test or a code snippet that produces this issue?

**Comment by zabihy** [comment]
```
private async Task<List<AccountIdEmailAddress>> FirstQueryAsync()
{
            var result = await _aeRepo.Join(
                _emailRepo,
                audienceEmail => audienceEmail.EmailId,
                email => email.Id,
                (audienceEmail, email) => new { email.FileDescriptionId, audienceEmail.SenderId })

                .Join(
                _fdRepo,
                prev => prev.FileDescriptionId,
                fileDesc => fileDesc.Id,
                (prev, fileDesc) => new { prev.SenderId, fileDesc.AccountId })

                .AsQueryable()
                .Union(

                _aeRepo.Join(
                _emailRepo,
                audienceEmail => audienceEmail.EmailId,
                email => email.Id,
                (audienceEmail, email) => new { email.FileDescriptionId, audienceEmail.RecieverId })
                .AsQueryable()
                )
                .GroupBy(p => new { p.AccountId, p.EmailAddress })
                .Select((s, index) => new AccountIdEmailAddress { Index = index, AccountId = s.Key.AccountId, EmailAddress = s.Key.EmailAddress })
                .ToListAsync();

            return result;
        }
```

**Comment by zabihy** [comment]
I have the same issue in SumAsync method that produces the following error:

**Comment by omarpiani** [comment]
Hi! sorry for my slowness.
I tested with 
`repo.GetAll().AsQueryable().ToListAsync();`
and you can simply get the problem with a less complex query.
Btw I can get a Task<IEnumerable> with 
`repo.GetAll().ToAsyncEnumerable().ToList()`
Let me know if is sufficent for you!

We feel a big lack of Async functions, hope we fill this gap soon.
