### ISSUE TITLE
Update SharpRepository.Ioc.Unity to use latest Unity container

### ISSUE THREAD

**Issue by NikolayYeryomenko** [SharpRepository/SharpRepository#184]
Now it uses Unity 2.1.505.2.
Can't execute:
RepositoryDependencyResolver.SetDependencyResolver(new SharpRepository.Ioc.Unity.UnityDependencyResolver(container));

**Comment by omarpiani** [comment]
I dropped Unity support, I knew Unity is an old microsoft project, does not support generics factory that we use, I think that last version of our package is not working.

I saw now that there is a community holding Unity alive. I take a look after SharpRepository 2.0 stable release.
For now I suggest to move to StructureMap, is quite more complex but fully complete (and tested in SharpRepository)

**Comment by omarpiani** [comment]
https://github.com/SharpRepository/SharpRepository/blob/master/SharpRepository.Ioc.Unity/UnityExtensions.cs here the code of last stable package @jtreuting , I can't remove from nuget with my credentials

**Comment by omarpiani** [comment]
I managed to create (with suffer, it's totally undocumented) a prerelease nuget package for Unity!!!
Using InstanceFactory the lifetime manager I'll pass is ignored, so this is not configurable. They are transient.
