### ISSUE TITLE
How to setup section in appsettings.json for Core?

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#185]
Hi!

I'm trying to use dependency injection with EfCoreRepository. I'm new to Core and can't figure out how to migrate my old web.config to appsettings.json. I would like to see an example config of a simple EfCore repo! 

That would help me along... currently I'm manually creating the repo in every controller using config.AddRepository("ef", new AppDbContext()).. and that works but not if I do services.UseSharpRepository(config) in Startup. Guess I need a appsettings.json section config for that.

Thanks!

**Comment by omarpiani** [comment]
there is a sample MVC Core project here!!! https://github.com/SharpRepository/SharpRepository/tree/develop/SharpRepository.Samples.CoreMvc

**Comment by omarpiani** [comment]
after appsettings.json look at Startup.cs and controller constructors

**Comment by GiganteX** [comment]
Thank you, Omar, I appreciate that! 
I looked for the appsettings.json info here previously, you could maybe a link there as well :
https://github.com/SharpRepository/SharpRepository/wiki/Getting-started
BR / GiganteX

**Comment by omarpiani** [comment]
getting started updated. Tnx
