### ISSUE TITLE
Update InMemoryRepository to Generate Primary Keys for Int64

### ISSUE THREAD

**Issue by jchampeau** [SharpRepository/SharpRepository#186]
I work with an existing MySQL database and use MS Entity Framework (i.e. Database First).  For the unit tests, I use SharpRepository.InMemoryRepository.  When Entity Framework generates the table classes, the primary keys get mapped to long data types (Int64).

The problem is that during unit testing, SharpRepository.InMemoryRepository does not generate primary keys for these classes because the are longs (Int64).

Would it be possible to update SharpRepository.InMemoryRepository.GeneratePrimaryKey() to handle Int64 data types for primary keys?  I think it would just be a matter adding another conditional similar to what was done for Int32, like the following:

```
if (typeof(TKey) == typeof(Int64))
{
    var pkValue = _items.Keys.LastOrDefault();
    var nextInt = Convert.ToInt64(pkValue) + 1;
    return (TKey)Convert.ChangeType(nextInt, typeof(TKey));
}
```

Alternatively, could the GeneratePrimaryKey() method be a protected member so that it could be overridden?

**Comment by omarpiani** [comment]
I think that all of them can be done, you can easily make a PR on develop branch

**Comment by omarpiani** [comment]
did in new release, soon I'll release packages
