### ISSUE TITLE
AutoFac InstancePerRequest() doesn't work

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#189]
This works:
builder.RegisterType<MyDbContext>().As<DbContext>();
But memory usage keeps increasing until out of memory, GC doesn't flush fast enough.

I want to create a new MyDbContext for every request (it's a REST api) to make sure the used ones are disposed ASAP.

Seems like this should do the trick, but when I use it the AutoFac fails to resolve the dbcontext:
builder.RegisterType<MyDbContext>().As<DbContext>().InstancePerRequest();

If I do this it works for one call, on the second it complains that the dbcontext is disposed....
builder.RegisterType<MyDbContext>().As<DbContext>().InstancePerLifetimeScope();

What could be wrong?

**Comment by GiganteX** [comment]
The entire method looks like this and it's called from globas.asx Application_Start():

public static void SetupAutoFacAndSharpRepository()
{
	var builder = new ContainerBuilder();

	// Get your HttpConfiguration.
	var config = GlobalConfiguration.Configuration;

	// Register your Web API controllers.
	builder.RegisterApiControllers(Assembly.GetExecutingAssembly());

	// OPTIONAL: Register the Autofac filter provider.
	builder.RegisterWebApiFilterProvider(config);

	// NOTE: SharpRepository : This one is to connect with SharpRepository
	builder.RegisterSharpRepository(); // you can specify name of repo or config section

	// works but eats all the memory
	//builder.RegisterType<DocDbContext>().As<DbContext>();

	// Set the dependency resolver to be Autofac.
	var container = builder.Build();
	config.DependencyResolver = new AutofacWebApiDependencyResolver(container);

	// NOTE: SharpRepository : to make the repository use autofac when it needs EF
	RepositoryDependencyResolver.SetDependencyResolver(new AutofacDependencyResolver(container));
}

**Comment by omarpiani** [comment]
Hi!
First of all, are you using SharpRepository2 and Autofac alpha package? Autofac factory is in alpha because only instantiates single key repositories.

An help extending it will be great!

Regarding your problem, are you building a .NET MVC app? It's quite sure you have some problems with Autofac, not SharpRepository. 
Reading documentation, register with InstancePerRequest is your solution, I think you are going in one of this problems.
http://autofaccn.readthedocs.io/en/latest/faq/per-request-scope.html#troubleshooting-per-request-dependencies

Try to get DbContext from autofac directly in your code have a  more clean study case!

**Comment by willhausman** [comment]
Was issue #93 ever addressed?  It's very old, but describes essentially the same problem.

**Comment by GiganteX** [comment]
But I could consider changing to another DI package it that works better. Would you suggest that , and if so which one? I only chose Autofac because I've heard that name so much ....

These are the packages I'm using: 
Autofac.WebApi2 4.1.0, 
Autofac 4.6.2, 
SharpRepository.EfRepository 1.4.7.2, 
SharpRepository.Ioc.Autofac 1.4.0, 
SharpRepository 1.4.7.2

Should I get the alphas instead?

It's a REST webapi, no MVC. 

Yes I think InstancePerRequest is the solution but then it fails to resolve.... 

Thanks for the link & info, Will and Omar! I will check it out, must go sleep, but will be back tomorrow with some progress hopefully!

**Comment by omarpiani** [comment]
You are right @willhausman !

You have I use and maintain StructureMap.

https://github.com/SharpRepository/SharpRepository/wiki/Getting-started#aspnet-mvc5-and-webapi

SharpRepository.Ioc.Mvc package installs MVC packages, but if not a problem, also configures StructureMap.

Place this class anywhere and app is configured
```
/// <summary>
/// Registers ContactsDbContext, that knows the connection string, as DbContext
/// </summary>
public class DbContexRegistry : Registry
{
    public DbContexRegistry()
    {
        For<DbContext>().Use(() => new ContactsDbContext("name=ContactsDbContext"));
     }
}
```

Late I will put hands on Autofac

**Comment by GiganteX** [comment]
Omar, 

I started by looking into these suggestions  to get it working with Autofac [https://github.com/SharpRepository/SharpRepository/issues/93]( #93) but did not get it to work. I got the "There is no DependencyResolver.Current" problem.

So I tried StructureMap, and BAM that just worked out of the box, no tricky configuration issues like I had with Autofac! A bit surprised but pleasantly so. I just added the DbContextRegistrry class and the ForRepositoreuesUseSharpRepository line and that was it!

But what about the InstancePerRequest thing? Does StructureMap handle that by default ie it doesn't reuse the dbcontext for every call like Autofac does? Because that's the critical point,  I want it to dispose the dbcontext for every new call so the IIS server doesn't run out of memory...

Oh and I noticed SharpRepository 2.02 is out of the alpha/beta! Very interesting. And the repository.json is now used for non-Core projects also. Well, why not!

**Comment by omarpiani** [comment]
Tnx, I did all to fast setup all! I really appreciate (positive) feedbacks!

Something is changed in recent releases of StructureMap
http://structuremap.github.io/object-lifecycle/supported-lifecycles/#sec5

There's a StructureMap.Web package, they suggest no longer to use, and my applications (webapi too) works well whitout that.

First paragraph in http://structuremap.github.io/object-lifecycle/supported-lifecycles/#sec0 says that Transient (the default) is same as PerRequest, so its what you need

**Comment by GiganteX** [comment]
Perfect! Thanks! :)
