### ISSUE TITLE
Custom repositories best practices?

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#190]
This needs a little updating regarding the new 2.02 version:
http://fairwaytech.com/2013/02/sharprepository-configuration/

The ConfigurationBasedRepository now requires a constructor like 
		public InvoiceRepository(ISharpRepositoryConfiguration configuration, string repositoryName = null) : base(configuration, repositoryName)
		{
		}

I am trying to figure out best practices regarding custom repositories. Would it be a good idea to add a constructor like this:

		public InvoiceRepository() : base (SharpRepositoryConfigFactory.GetConfig())
		{
		}

That should init it with the default config right, from repository.json?

Ok question 2, how can I inject this custom InvoiceRepository into a controller? Because Autofac/StructureMap injects a IRepository<Invoice,int> .... ? Sorry for dumb questions...

**Comment by omarpiani** [comment]
@jtreuting blog is valid for version 1.x versions, but you can find a lot of good informations still valid.

If using default reposiroies is not your solution, the right way to customize a repository is extend the repoistory you like and then create your own factory, coping and customizing from the repository you what to extend and then set the factory class name in your repository.json!

Thats not a dumb question

**Comment by GiganteX** [comment]
Aaa yes you're right , the factory is there in the settings, that's great!! Thanks! :) I'll play around with it and see what I can do.

Could you give an example of how to extend? not sure I follow you...

**Comment by omarpiani** [comment]
not now, about Tuesday!

**Comment by GiganteX** [comment]
Hmm.. ok a follow-up to that. not really custom repository related but more about StructureMap ... what if I have two databases and two controller? This line only takes one repository:
MvcDependencyResolver.ForRepositoriesUseSharpRepository("repository.json", "sharpRepository");

How can I get it to inject controller 1 with a repository using a config that uses a dbcontext for database 1, and controller 2 with  a repository using the config for database 2 ?

**Comment by omarpiani** [comment]
Not so easily.

You can configure StructureMap in many ways whit some conditional or named resolution, but MVC DependencyResolver does not accept parameters. https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.EfRepository/EfConfigRepositoryFactory.cs is the last your hope.

You have many ways. for instance you can copy factory and customize GetDbContext method in https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.EfRepository/EfConfigRepositoryFactory.cs

**Comment by GiganteX** [comment]
Ok, I'll take a look at that, if I can't get it to work easily maybe I'll keep my current "solution" where I don't inject it in controller 2 but create that repository manually. It works, but it's not as pretty. :)
Thanks!

**Comment by omarpiani** [comment]
created https://github.com/SharpRepository/SharpRepository/wiki/Custom-Repositories
