### ISSUE TITLE
includePaths?

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#192]
Hi!

How can I add multiple includePaths?

This works:
repo.Get(id,includePaths: x => x.Employee);

Then I want to add some more includePaths, and I don't understand the syntax for doing that....

**Comment by omarpiani** [comment]
includePaths is a "params", so you can add more includes with this (ugly) solution:

``` 
repository.Get(id, includePaths: new Expression<Func<Contract, object>>[] { c => c.Employee, c => c.Employee2 });
```

or with better

```
repository.Get(id, "Employee", "Employee2" });
```

or with old way

```
var strategy = new GenericFetchStrategy<Contract>();
strategy.Include(x => x.Employee);
strategy.Include(x => x.Employee2);
var contract = repository.Get(id, strategy);
```

**Comment by GiganteX** [comment]
Aah that makes sense. That first solution looks a bit ugly yes, but with the second solution it is possible to misspell the name and you will only know at runtime. In the first solution there is syntax/intellisense checking for the names. 
Hm maybe I will use the third solution then! :)
Oh and maybe add this to the documentation as well? I could not find it in the wiki and I think it's really useful information!
Thanks!

**Comment by omarpiani** [comment]
I did https://github.com/SharpRepository/SharpRepository/wiki/EF-Lazy-Loading

**Comment by GiganteX** [comment]
Great stuff! Tiny error at the bottom:
"spec.FetchStrategy
                .Include(x => x.Employee);   <--- semicolon should be removed
                .Include(x => x.Owners.First().Address);"
