### ISSUE TITLE
MongoDbRepository converts array to string while updating

### ISSUE THREAD

**Issue by esmn** [SharpRepository/SharpRepository#193]
On the core 2.0 project, we are using MongoDbRepository. In our entity we have string[] property. While adding a new data, there is no problem with an array, it successfully added to db as an array. But when we try to update same entity, even we don't touch the array property, it converts array property to string and store it as a string. 

Before update:
![capture](https://user-images.githubusercontent.com/37136483/37079971-a436d6e8-21f5-11e8-96e5-f8ca42c7e3b4.PNG)

After update:
![capture3](https://user-images.githubusercontent.com/37136483/37079928-737b22b6-21f5-11e8-8d40-acc6374aadc6.PNG)

When we try to get updated data, we are getting an error, it says "Cannot deserialize a 'String[]' from BsonType 'String'.'".

Then we added representation attribute to string[] property. `[BsonRepresentation(BsonType.Array)]`
Now throws different error and it says "Array is not a valid representation for a StringSerializer".

How should we store and update an array property in mongoDb using MongoDbRepository?

**Comment by omarpiani** [comment]
seems a MongoDb.Driver usage problem.

I found this guy storing as array:
https://dotnetcodr.com/2016/04/21/introduction-to-mongodb-with-net-part-14-object-serialisation-in-the-net-driver/

Try this:
IEnumerable<string> Images{ get; set; }

Remember to clean data before try

**Comment by esmn** [comment]
@omarpiani Thank you for your quick response but unfortunately it didn't work out. Still getting similar error, now it says "Cannot deserialize a 'List<String>' from BsonType 'String'".

I don't think this issue related with MongoDb.Driver usage. In your source code, in MongoDbRepositoryBase class, you use StringSerializer in couple places(include UpdateItem and Initialize methods). You didn't use StringSerializer in your AddItem method and It works just fine with arrays. On the other hand, in UpdateItem method you use StringSerializer for some reasons and it fails to update arrays (updates arrays as string). Not sure but this may cause the issue?

**Comment by omarpiani** [comment]
need some time to study this 🐙

**Comment by omarpiani** [comment]
after update https://github.com/SharpRepository/SharpRepository/issues/194 with released mongo nuget package 2.0.3-beta1 I think this problem is resolved.

I added a branch with sample project using email as string array: 
 https://github.com/SharpRepository/SharpRepository/tree/emailsAsStringArray/SharpRepository.Samples.CoreMvc
