### ISSUE TITLE
Any example using console app?

### ISSUE THREAD

**Issue by mathpaquette** [SharpRepository/SharpRepository#197]
Hello, trying to figure out how to use SharpRepository for a Console App with IoC (Simple Injector in this case). I have something like this:

```
var config = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("repository.ef.json")
                .Build();

            var section = config.GetSection("sharpRepository");
            ISharpRepositoryConfiguration sharpConfig = RepositoryFactory.BuildSharpRepositoryConfiguation(section);

            _container = new Container();
            _container.Register<ScannerController>();
            _container.RegisterSharpRepository(sharpConfig);

            _container.Verify();
```

But I have this exception verifying the container.

System.InvalidOperationException: 'The configuration is invalid. Creating the instance for type ScannerController failed. The constructor of type ScannerController contains the parameter with name 'scannerRepository' and type IScannerRepository that is not registered. Please ensure IScannerRepository is registered, or change the constructor of ScannerController.'

This thing is my IScannerRepository implements the IRepository<Scanner, int> but in another assembly of my startup file.
```
public interface IScannerRepository : IRepository<Scanner, int>
    {
        
    }
```

If anyone can help please.

Thank you.
Mathieu

**Comment by mathpaquette** [comment]
Okay, I realized that custom repository need to be register by hand...

**Comment by omarpiani** [comment]
btw Benchmark app is a console app https://github.com/SharpRepository/SharpRepository/tree/develop/SharpRepository.Benchmarks.Configuration
