### ISSUE TITLE
Question regarding concurrent issues with SharpRepository and EF6

### ISSUE THREAD

**Issue by mathpaquette** [SharpRepository/SharpRepository#201]
I think I'm experiencing concurrency issues and don't know how to deal with, at least with SharpRepo. In fact, 2 of my services (Level1MarketDataService and ScannerService) are using IContractRepository at the same time to retrieve or create unexisting contracts. I'm using TryFind to check whether or not if the contract exists. Well, I'm having really strange behavior, i.e. even if the contract exists in the DB sometime it returns false! 

Also, I'm wondering if it's a good practice or not to have to override the AddItem for EF repo in order to Attach some existing entity in the context. 

Can someone have a look at my project I would really appreciate if I can improve my design?

https://github.com/mathpaquette/PT.MarketDataService/blob/contracts/src/PT.MarketDataService.Core/DomainServices/Level1MarketDataService.cs

Thank you very much in advance.
Mathieu

**Comment by omarpiani** [comment]
Hi. Is possible to write a in you project a test that reproduce the "strange behavior", I think it's a problem whit DbContext.

**Comment by mathpaquette** [comment]
@omarpiani good idea. ill do that tomorrow. I have a demo today!

**Comment by mathpaquette** [comment]
Ill come with a full description of my problem.
