### ISSUE TITLE
How can I create indexes or alternatively access collection instance of any type in MongoDbRepository?

### ISSUE THREAD

**Issue by svncsvr** [SharpRepository/SharpRepository#202]
I need to create TTL index on a field of the document.
Does SharRepository provide a method for this?
or provide some ways for accessing my type's mongo collection object?

**Comment by omarpiani** [comment]
For me SharpRepository is not responsible of creation of collections and indexes (like in EntityFramework). 
It helps you in CRUD operations.
You have to create it with common MongoDb.Driver library features

Someone here asks something like yours:
https://stackoverflow.com/questions/43199438/setting-time-to-live-ttl-in-azure-documentdb-using-mongodb-driver-2

May be @tresoldigiorgio will help you

**Comment by omarpiani** [comment]
more than 1 month. Closed
