### ISSUE TITLE
2.x Upgrade Count() Issue

### ISSUE THREAD

**Issue by tynorton** [SharpRepository/SharpRepository#204]
I just tried upgrading our SharpRepository packages to 2.x and ran into an exception.

I traced it down to `SharpRepositoryBase.Count(ISpecification<T> criteria)`.

![image](https://user-images.githubusercontent.com/811086/40168275-f3976400-5977-11e8-8707-8aca212928a4.png)

Compare that `Count(ISpecification<T> criteria)` to 1.5.0.2's: https://github.com/SharpRepository/SharpRepository/blob/1.5.0.2/SharpRepository.Repository/RepositoryBase.cs#L826

So at some point all of the `Expression<>`s were compiled into `Func<>`s. I wondered why.

So, I tracked down the change in question: https://github.com/SharpRepository/SharpRepository/commit/8c1f9aaf5c23e82e91621adf8762ce6c71d620a9#diff-d24380b902ea13a619155432be3b7b18R841

Looks like this was done as part of a change to handle differences in NETSTANDARD vs NETFX reflection/types. 

But, in our case, broke what was working.

Is that `Compile()` necessary? If not we should probably revert to the old method which doesn't throw (See below where `predicate` is the `Func<>`).

![image](https://user-images.githubusercontent.com/811086/40167855-f1354d68-5976-11e8-8d95-0f70b84ef429.png)

**Comment by omarpiani** [comment]
Thank you!

It was in the original huge work by @eloekset .
I use Count in my project with and without predicates and I don't have any exception. 
Do you think you (we) can reproduce this exception in a unit test?

**Comment by tynorton** [comment]
@omarpiani, the bug only happens with the `Count(ISpecification<T> criteria)`. Is your project NETFX? NETSTANDARD?

I'm not sure I have much more time to dedicate to this to create a test, but I will see.

**Comment by omarpiani** [comment]
? project is both .NET Framwork and .NET Standard

**Comment by omarpiani** [comment]
Released 2.0.4.2 stable.

Write something if there are problems
