### ISSUE TITLE
Selector not working

### ISSUE THREAD

**Issue by neman** [SharpRepository/SharpRepository#207]
I'm using EFCoreRepository

I tried selector with GetAll and FindAll, but it seems that it does not work. It always creates SQL query with all columns, instead of selector specific columns.
Even simple example like this
`var test = GetAll(x=>x.Id)`

or

`var test = FindAll(selector: selector=>selector.Id)`

query all columns, instead of just Id column value.
Looks like selector is selecting from memory, and not from database. Is this true?

How can I make projections with SharpRepository so that my generated sql query contains only selected columns?

Did I skip some configuration steps?

## **EDIT**

I did some investigation. It seems that this commit broke the functionality https://github.com/SharpRepository/SharpRepository/commit/c082ae65#diff-d24380b902ea13a619155432be3b7b18L289
Select is now IEnumerable, instead of IQueryable

Current code
![image](https://user-images.githubusercontent.com/350314/40393374-6c6bc74e-5e1f-11e8-8c30-0ce9b10f87f1.png)

Previuos code

![image](https://user-images.githubusercontent.com/350314/40393487-eed4e2c4-5e1f-11e8-9d6b-cf58b995f8b0.png)

Why is this query Compiled?
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/compiled-queries-linq-to-entities

I think this should be used https://cmatskas.com/improve-ef-core-performance-with-compiled-queries/

**Comment by omarpiani** [comment]
probably is related to #204 

Give me some time to investigate

**Comment by eloekset** [comment]
I should run some manual tests for PR #208 this evening to verify that the revert doesn't have any impact on .NET Core Mac/Linux. Right now it seems like the change was done for no good reason, as part of making the library .NET Standard compatible.

**Comment by omarpiani** [comment]
just released SharpRepository.Repository version 2.0.4.1-beta2 with this commits. Let me know ok works

**Comment by eloekset** [comment]
If you've already got a project that makes use of this functionality, @neman, it would be great if you could test the beta release and verify that correct SQLs are executed. I started updating my manual test project still on xproj yesterday, but I didn't get time to finish it.

**Comment by eloekset** [comment]
In between other things, I've done a super simple test for a GetAll selector in a new project using EFCore 1.1.5 on .NET Core 1.1.

It seems to work as expected now:
![image](https://user-images.githubusercontent.com/791721/40483379-12d96dbe-5f58-11e8-9174-f00e4dd96802.png)

Still it would be great to have it better tested.

**Comment by neman** [comment]
It works fine for GetAll and FindAll. I agree that there should be written some unit/integration test for this. 
How would you test this case, it is an interesting theme.

**Comment by omarpiani** [comment]
test directly the query produced setting up a logger in DbContext as in https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Tests.Integration/Spikes/EfLazyLoadSpike.cs and https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Tests.Integration/Spikes/EfLazyLoadSpike.cs

**Comment by neman** [comment]
Shoud we create new test file, EfCoreSelectorTest.cs?

**Comment by omarpiani** [comment]
seems the most obvious solution

**Comment by omarpiani** [comment]
pushed 2.0.4.2 release.

Tnx to all

**Comment by neman** [comment]
I must open this again.
Selector is now working fine with GetAll and FindAll, but it's not working with Get and Find.

**Comment by omarpiani** [comment]
In Get and Find this portions of code
```
 var result = FindQuery(context.Specification, context.QueryOptions);
 if (result == null)
   return default(TResult);

 var results = new[] { result };
 return results.AsQueryable().Select(context.Selector).First();
```
obviously on " var results = new[] { result };" row query is executed and AsQueryable() can't change this.

we must do FindQuery<TResult>(context.Specification, context.QueryOptions, context.Selector);

That propagates necessary ovverrides in all "non LinqRepositoryBase" repositories, this Job connects with problems in #126

**Comment by omarpiani** [comment]
I released prerelease nuget package for all repositories, I wait all you (expecially @jtreuting ) feedbacks!

**Comment by omarpiani** [comment]
After so long time I suppose there is no problem
