### ISSUE TITLE
how to use Detached in SharpRepository.EFRepository

### ISSUE THREAD

**Issue by 15768495614** [SharpRepository/SharpRepository#210]
hello,
   
![b o3bd851ezc_p jd o 0e](https://user-images.githubusercontent.com/39647869/40575434-98a24e0a-6117-11e8-8e96-af15b7449d0e.png)
 this is my code.
when use Json.Net go to serialize,program foreach select  to sql server.
I need detached this list.
how to writer code.

**Comment by 15768495614** [comment]
有人吗

**Comment by omarpiani** [comment]
You are talking about detached entity state? 
`
dbContext.Entry(entity).State = EntityState.Detached;
`
Btw serializing is a normal operation.. ther's a way you can do it without detaching.. 

You need to access it instantiating a new one or better accessing it via dependency injection.

OT:
where you placed this method? i suggest you to use c# extensions to use 

`public List<Order> GetOrderList(this IRepository<Order,int> repository, DateTime startTime, bool active)`
