### ISSUE TITLE
Redis cache flush automatically old generation keys

### ISSUE THREAD

**Issue by tresoldigiorgio** [SharpRepository/SharpRepository#212]
The repository clean automatically superseeded generation keys or
i have to configure redis to do that?

Thanks

**Comment by omarpiani** [comment]
Dunno this.. 
Redis caching provider implementation has few lines ok code... 
 I think you can answer easily https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Caching.Redis/RedisCachingProvider.cs

probably the answer is in the library we use https://github.com/StackExchange/StackExchange.Redis

Let me know how you resolve!
