### ISSUE TITLE
There is no configuration specified for Microsoft.Extensions.Caching.Memory.IMemoryCache

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#213]
Hi!

I'm making a .NET Framework application, playing around with the inMemory repository. Standard repository.json from the samples. Also using StructureMap:

MvcDependencyResolver.ForRepositoriesUseSharpRepository("repository.json", "sharpRepository");

It works fine with the inMemoryNoCaching repository, but when using inMemory repository I am getting this exception:

"There is no configuration specified for Microsoft.Extensions.Caching.Memory.IMemoryCache"

It also says:
"Could not resolve type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' using the 'StructureMapRepositoryDependencyResolver'.  Make sure you have configured your Ioc container for this type."

That makes sense, but I can't figure out how to do that. Please advice?

**Comment by omarpiani** [comment]
Create a StructureMap public Registry that instantiates  anywhere in your code.

```
 public class MemoryCacheRegistry : Registry
    {
        public MemoryCacheRegistry ()
        {
            For<IMemoryCache>().Use(() => new MemoryCache(new MemoryCacheOptions())).Singleton();
        }
    }
```

I think you need Singleton.. evaluate well.. it shares memory cache through user sessions..

**Comment by omarpiani** [comment]
you put the Singleton()?

Try this
```
 public class MemoryCacheRegistry : Registry
    {
        public MemoryCacheRegistry ()
        {
            var memoryCache = new MemoryCache(new MemoryCacheOptions());
            For<IMemoryCache>().Use(memoryCache);
        }
    }
```

**Comment by GiganteX** [comment]
Yes I tried with the Singleton().

Now I trired your other solution, it did not work, unfortunately...

**Comment by GiganteX** [comment]
I can give you the code? It's a small test-project.

**Comment by omarpiani** [comment]
let me see in a github repository.. but using inMemory (that uses MemoryCache) and caching it with MemoryCache is a nonsense

**Comment by GiganteX** [comment]
Omar, I uploaded it here:

https://github.com/GiganteX/test_InMemory

Thanks!!

**Comment by omarpiani** [comment]
sooorrryyy..  I did a mistake.
InMemoryRepository does not uses MemoryCache (can be done with CacheRepository). It uses a Collection inside repository that itself must be "Singleton" with 
```
MvcDependencyResolver.ForRepositoriesUseSharpRepository("repository.json", "sharpRepository", null, Lifecycles.Get<SingletonLifecycle>() );
```

in Global.asax.cs

I suggest to deactivate caching, that requires an IMemoryCaching registered in StructureMap, because in this case you are caching in same memory.

I made a pull request in your project (please push solution too next time!)

**Comment by GiganteX** [comment]
Thanks!! I think I understand how the repository.json configuration works now, and why it had cache on cache...

And now it all works as it should!

I realize now that the repo doesn't build easily, sorry about that!
