### ISSUE TITLE
Specify Collection Name With MongoDbRepository

### ISSUE THREAD

**Issue by rerikson** [SharpRepository/SharpRepository#215]
Is it possible to specify the name of the collection a MongoDbRepository uses?  Right now it seems that the  name of the collection in the database must match the C# TypeName exactly.

**Comment by omarpiani** [comment]
Hey.. as many time happens with MongoDb, I didn't find easily how can be done.

The first step is make with the MongoDB.Driver.

http://mongodb.github.io/mongo-csharp-driver/2.6/

If you can configure it with bson mapping to your model http://mongodb.github.io/mongo-csharp-driver/2.6/reference/bson/mapping/ MongoDbRepository will not be changed.

Anyone never handled this? @esmn @svncsvr @tresoldigiorgio

**Comment by tresoldigiorgio** [comment]
Is not possible now directly with sharpRepository.
Can be useful to have an attribute like "[MongoCollectionName("name")]" and in MongoDbRepositoryBase 
change the method BaseCollection()

**Comment by omarpiani** [comment]
Ye.. but how can be done with MongoDb.Driver?!

**Comment by tresoldigiorgio** [comment]
In MongoDB driver the only way is to get collection with a different name 
database.GetCollection<Entity>("myentities")

**Comment by rerikson** [comment]
Thank you both for the quick responses.  The attribute approach sounds like a good plan. I can try and get a PR put together around that if you would like?

**Comment by omarpiani** [comment]
http://mongodb.github.io/mongo-csharp-driver/2.4/reference/bson/mapping/conventions/ an approach can be use the IClassMapConvention to read our [MongoCollectionName("name")]

Next week I'm in holidays! @rerikson, I hope to find a great PR when I return! 😀

**Comment by tresoldigiorgio** [comment]
I've write the code but i need other time to test....

**Comment by tresoldigiorgio** [comment]
#218

**Comment by omarpiani** [comment]
Uhhu! is looking good! BTW a unit test is needed!

**Comment by omarpiani** [comment]
add in https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Tests.Integration/Spikes/MongoRepositorySpikes.cs

**Comment by omarpiani** [comment]
@tresoldigiorgio you saw my PR to update your PR? :octocat: 
Problems?

**Comment by tresoldigiorgio** [comment]
all ok! sorry for the delay!

2018-07-04 10:13 GMT+02:00 Omar Piani <notifications@github.com>:

**Comment by omarpiani** [comment]
Pushed package 2.0.7.1-beta1 with new Attribute, in addition updates to Mongo Driver 2.7.0 that supports MongoDb 4.0

Let me know when is ready to go.
