### ISSUE TITLE
SharpRepository.Caching.Redis 2.0.2.1 need a new version of SharpRepository.Repository pack

### ISSUE THREAD

**Issue by tresoldigiorgio** [SharpRepository/SharpRepository#220]
In ICachingProviderConfiguration i've added a new method ContainsKey used in Caching.Redis so the pack depends on a new version of SharpRepository.Repository pack. Can you release a new version?

**Comment by omarpiani** [comment]
Right, sorry,  updated repository to 2.0.4.3 and also updated to 2.0.2.2 that requires him.

**Comment by omarpiani** [comment]
Tried?

**Comment by tresoldigiorgio** [comment]
yes, works!

2018-07-17 9:36 GMT+02:00 Omar Piani <notifications@github.com>:
