### ISSUE TITLE
Manage transactions with SQL

### ISSUE THREAD

**Issue by erangasandaruwan** [SharpRepository/SharpRepository#229]
What would be the best way to manage transaction with the below scenario ? I just have written kind of a pseudo code below. Can we achieve transactions/ unit of work with different repositories with "SharpRepository" ?  

**__var lastSequence = sequenceRepo.Find(.....);

lastSequence.SequenceNumber + 1;

sequenceRepo.Update(lastSequence);_**

**Comment by omarpiani** [comment]
Hi, https://github.com/SharpRepository/SharpRepository/blob/b63634b805e7bae61e46c3374ce0dda194168227/SharpRepository.Tests.Integration/RepositoryAddTests.cs here there some example!

**Comment by omarpiani** [comment]
Sorry for late reply!

**Comment by omarpiani** [comment]
Different entity framework repositories?

**Comment by erangasandaruwan** [comment]
Hi @omarpiani,

Thank you very much for the reply. Yes we may using different repositories and hope we could manage everything withing the transaction scope as per the below example since we are using Entity framework.

Thanks again.. 

using (var trans = new TransactionScope())
{
          var employee = employeeRepo.Find(.....);
          var increment = incrementRepo.Find(....);
          employee.Salary = employee.Salary + increment;
          employeeRepo.Update(employee);
}
