### ISSUE TITLE
Can i use SharpRepository with winforms Application?

### ISSUE THREAD

**Issue by dabasdev** [SharpRepository/SharpRepository#230]
Can i use SharpRepository with winforms Application using EF Core ?
if yes , how can implement that ?

**Comment by omarpiani** [comment]
You need to make a project that supports https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/ and https://www.nuget.org/packages/SharpRepository.EfCoreRepository/ requirements.

As written in https://docs.microsoft.com/it-it/dotnet/standard/net-standard you can run EF Core 2.0 with .NET Framework 4.6.1, with .NET Framework 4.6 our repository installs EF Core 1.1.

Remember that current preview .NET Core 3.0 supports natively WinFroms https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#windows-desktop

**Comment by dabasdev** [comment]
> 
> 
> You need to make a project that supports https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/ and https://www.nuget.org/packages/SharpRepository.EfCoreRepository/ requirements.
> 
> As written in https://docs.microsoft.com/it-it/dotnet/standard/net-standard you can run EF Core 2.0 with .NET Framework 4.6.1, with .NET Framework 4.6 our repository installs EF Core 1.1.
> 
> Remember that current preview .NET Core 3.0 supports natively WinFroms https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#windows-desktop

Can u give me a sample project in winforms , please?

**Comment by omarpiani** [comment]
Be more clear, on your needings, why you need EF Core and not EF6?

**Comment by dabasdev** [comment]
I need to understand how can implement this Repository in WinForms of Wpf (Desktop Applications)

**Comment by omarpiani** [comment]
so you don't need Entity Framework **Core**

**Comment by dabasdev** [comment]
whatever using EF Core or EF6 .

**Comment by dabasdev** [comment]
> 
> 
> I pushed a really simple winforms with EfRepository on https://github.com/omarpiani/FormsSharp
> 
> Remember to `Update-Database` from Package Console

thank u so much bro

**Comment by omarpiani** [comment]
ur wellcome!
