### ISSUE TITLE
Documentation 404 not found.

### ISSUE THREAD

**Issue by VictorioBerra** [SharpRepository/SharpRepository#231]
https://github.com/SharpRepository/SharpRepository/wiki/Getting-started#configuration-options

This link: http://www.fairwaytech.com/2013/02/sharprepository-configuration/

**Comment by jtreuting** [comment]
I'm looking into it.  My company just launched a new website and it looks like the blog links might have got changed.

**Comment by omarpiani** [comment]
for now.. https://web.archive.org/web/20170803144936/http://www.fairwaytech.com/2013/02/sharprepository-configuration/

**Comment by VictorioBerra** [comment]
Another one for you @omarpiani 

https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Repository/Specifications/CompositeSpecification.cs#L9

**Comment by jtreuting** [comment]
For the original link there was a missing redirect when we launched a nw site.  It is fixed now.

**Comment by omarpiani** [comment]
grats for your new stunning website 😮
