### ISSUE TITLE
Serialized critrerias

### ISSUE THREAD

**Issue by avifatal** [SharpRepository/SharpRepository#232]
Hi,
1. When it comes to working with REST API, I wonder if its possible to some how pass the entire criterial from the client side, over HTTP. Im planning to use MongoDb.

2. I need to apply row level security, Is it possible to somehow inject constraints to every fetch/ update/delete calls?
So let's say that all entities have TenantId, so I want to enforce another `where clause` on the criteria that will bring only rows that has the constraint TenantId.

Thanks

**Comment by omarpiani** [comment]
Filter data and check security is my favorite usage of SharpRepository, effectivelly there's not an example of this. I make this with `Specifications` 

Best documentation for now are the tests:

Work with Specifications:
https://github.com/SharpRepository/SharpRepository/blob/b63634b805e7bae61e46c3374ce0dda194168227/SharpRepository.Samples/HowToUseSpecifications.cs

Filtering with specifications:
https://github.com/SharpRepository/SharpRepository/blob/b63634b805e7bae61e46c3374ce0dda194168227/SharpRepository.Tests.Integration/RepositoryFindAllTests.cs#L18


For checking if a new object is valid:
https://github.com/SharpRepository/SharpRepository/blob/b63634b805e7bae61e46c3374ce0dda194168227/SharpRepository.Tests/Specifications/SpecificationTests.cs

**Comment by omarpiani** [comment]
```
var specs = new Specifications<MyEntity>(allRecords => true); // retrieves all records

if (!user.IsAdmin()) specs.Predicate.And(e => e.TenantId == user.TenantId); // filter my user tenantIds

var myEntities = repo.FindAll(specs);
```

**Comment by avifatal** [comment]
Great, I will dig into that. Can you please answer number 1?

When it comes to working with REST API, I wonder if its possible to some how pass the entire criterial from the client side, over HTTP. Im planning to use MongoDb.

**Comment by omarpiani** [comment]
If I have undestand seems your application behaviour problem.. you have to write your own function that integrates data from json to an C# predicate (Expression<...,bool>), Json is data, predicate is a function (that takes in input json?)

Can be there is a common pattern for this, but this is too specific and don't have any correlation with SharpRepository. Maybe StackOverflow is right place for this subproblem

**Comment by jtreuting** [comment]
There is also the opportunity to use Hooks to do this as well.  Here is a blog post with some examples: https://blog.fairwaytech.com/2014/01/getting-your-hooks-into-sharprepository
