### ISSUE TITLE
Constructor on CacheRepository.CacheConfigRepositoryFactory not found

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#233]
Hi!

NET Core 2,1 . Been using InMemory repo for some stuff, works fine but when creating new repo object = all is gone, repo is empty. Even though I've tried the built-in caching (timout/standard). That didn't do anything at all (is it supposed to?). Trying instead to get some caching going with the pre-release of CacheRepository but I got this during creation of the repo object:

"Constructor on type 'SharpRepository.CacheRepository.CacheConfigRepositoryFactory' not found."

Is it a known eror?

The config looks like this (only relevant part cut out):

      "cacheRepo": {
        "factory": "SharpRepository.CacheRepository.CacheConfigRepositoryFactory, SharpRepository.CacheRepository",
      },

...so very basic. I'm thinking it's an error because it's a pre-release so it just doesn't work yet? What's the plans to get it working?

Thank you!

**Comment by omarpiani** [comment]
So there are two questions!? If you want that InMemoryRepository you have to register InMemoryRepository as Singleton in `Startup.cs`
I noticed that services.UseSharpRepository can't autosetup as Singleton like .NET can, I will fix it later. You must make manually with` services.AddSingleton<IRepository<Contact>, InMemoryRepository<Contact>>();`

For cache repository surelly is untested, I will fix later too.

**Comment by GiganteX** [comment]
Hi Omar!

I've tried it as a singleton in a .NET Framework project, like this:
	MvcDependencyResolver.ForRepositoriesUseSharpRepository("repository.json","sharpRepository",null,Lifecycles.Singleton);

...but it didn't work. In my controller constructor I seed the repo with some objects, and in the Index() method I list the contents, and it's always the same no matter how many times I call it. Even though it's a singleton. It should have added up. So I guess something is broken. 

Also, I can tell StructureMap to inject a singleton repo into the controller, but when I create it manually with RepositoryFactory.GetInstance<>() I can't specify that, so then I get a non-singleton? Or it there another way to get that singleton repo manually?

I tried the AddSingleton() line in my .NET Core project but I got an exception :
StructureMapConfigurationException: No default Instance is registered and cannot be automatically determined for type 'ICachingStrategy<Book, String>'

What can I do?

**Comment by omarpiani** [comment]
you have to use ~DependencyResolver.Current.GetService<IRepository<Type>>();` if you want the autoconfiguration.

If you want to use Repository factory must be used with the correct configuration when you call `RepositoryFactory.GetInstance<T,TKey>(config)`
