### ISSUE TITLE
XMLRepository samples/documentation

### ISSUE THREAD

**Issue by brandonmcclure** [SharpRepository/SharpRepository#237]
I would like to use the XMLRepository for my project and would like documentation on how to properly use it.  

For my use case, I want to use XMLRepository as I am prototyping and then switch out for a repository backed by a RDMS as needed when/if my project needs to grow. 

See this [SO question](https://stackoverflow.com/questions/56620740/how-can-i-use-the-sharprepository-to-create-a-local-filesystem-repository-of-my/56794381#56794381) for some more context.

**Comment by omarpiani** [comment]
https://github.com/SharpRepository/SharpRepository/wiki/XmlRepository-Documentation
