### ISSUE TITLE
Use LinqRepositoryBase for 2 tables?

### ISSUE THREAD

**Issue by fzhangddt** [SharpRepository/SharpRepository#238]
Hi,

I am using LinqRepositoryBase and .net 4.6. The backend is MS sql server. I have a situation like this:

1) Table "Profiles", which describe details of a profile, columns: Id, Name, Description, etc.
2) Table "ProfileToParts", Columns: ProfileId, UserId, NumberOfParts. It shows for a particular userId, how many parts are associated with a profile. So due to the user's permission, different userId could have different number of parts even for the same ProfileId.

I use Kendo Grid on the front end to display the list of profiles and its associated NumOfParts. Kendo Grid allows the user to filter, sort and pagination of columns (including NumOfParts column). We translate Kendo's filter, paging and sort into SharpRepository's ISpecification and PagingOptions. And then we call FindAll(ISpecification and PagingOptions).

When the repository wraps a single table, FindAll() will execute the filter, sort, paging inside sql server. This is very efficient because Profiles table can be big. Running filter, sort and paging inside sql server is faster than returning all rows to C# memory, and filter/sort/paging against the objects.

But the situation is different here:  the NumOfParts we need is from a different table, so we have to join that table. I wrote a table valued function to wrap up the table join and take userId as a input parameter. But FindAll() no longer does filter/sort/paging inside sql server. Instead, it calls TVF and retrieves all rows and bring all rows to C# memory and then filter/sort/paging. I guess Linq to Sql decides not to execute them in sql.

One solution is to Add UserId and NumOfParts column to Profiles table and delete ProfileToParts table, which is de-normalize. But the drawback is when there are many userIds, the table repeats many columns except UserId and NumOfParts columns. Then FindAll() should be able to store execute in sql server instead of client execute. This solution sacrifices the space in sql server to gain perf.

Is there any way I can use LinqRepositoryBase to have table join? Or any other suggestions?

In my case, I don't need to add/insert/delete Profile, I only do select.

Thank you very much!
Frank

**Comment by omarpiani** [comment]
Sorry for late reply, Sometime suggest to make a view that calls your TVF to keep performance issues outside ORM in general, than you have a repository for index/search and a repository for edit data.
Not sure is the right solution here, I have to put hands on it.
