### ISSUE TITLE
Again I struggle with the right way of initializing....

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#241]
It's a C# Core console application. I have a configuration-based custom repo that looks like this:

```
{
  "sharpRepository": {
    "repositories": {
      "default": "ef",
      "ef": {
        "factory": "SharpRepository.EfCoreRepository.EfCoreConfigRepositoryFactory, SharpRepository.EfCoreRepository",
        "connectionString": "server=xxx;user id=xxx;password=xxx;database=xxx", 
        "dbContextType": "Integration.IntegrationDbContext, Integration" 
      }
    }
  }
}

```

and I do this:

```
			var config = new ConfigurationBuilder()
				.SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
				.AddJsonFile("repository.json")
				.Build();

			var section = config.GetSection("sharpRepository");
			ISharpRepositoryConfiguration sharpConfig = RepositoryFactory.BuildSharpRepositoryConfiguation(section);

			var irepo = new IntegrationRepository(sharpConfig);

```

and I get this at that last line when trying to create the repository:

`SharpRepository.Repository.Configuration.ConfigurationErrorsException: 'The EfCore repository Factory gets DbContext or DbContextOptionBuilder from RepositoryDependencyResolver containing the Ioc container passing directly DbContextOptions'
`
Why is it not getting that information from the repository.json file? Hmm ok it doesn't have the DbContextOptions with the UseSqlServer() line...  How do I get that in there.. the right way?

If it was a REST API I'd do that services.AddDbContext() thing.... but I have no services object here...

And I tried the StructureMap Registry thing, but it's not getting called.... I guess I need to use that RepositoryDependencyResolver ? What should it look like?

**Comment by omarpiani** [comment]
Actually EfCoreRepository (unlike EfRepository) force to have a configured dependency resolver, with dbContext service, at least a service for the DbContextOptions parameter.

Viewing the code now seems legit to have the possibility to dinamically instantiate DbContextOptions with the passed connection string.. it's a good but not so easy change.

**Comment by omarpiani** [comment]
ok, EfCore supports multiple implementations, for instance, you configure a sqlserver with https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer package, passing UseSqlServer options.

EfCoreRepository does not have Microsoft.EntityFrameworkCore.SqlServer package and can't do this, so you have to pass via dependency resolver the DbContextOptions

**Comment by GiganteX** [comment]
Ok... Can you show how to do that? How to initialize the dependency resolver?

**Comment by omarpiani** [comment]
https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Samples.CoreMvc/Startup.cs#L33

is a customrepository sample and

https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Samples.CoreMvc/Startup.cs#L37

is setups dependency resolvers in one line

**Comment by GiganteX** [comment]
Yes, but that is sample for MVC. I've got that working. This is a console application. I could create a new ServiceCollection and do services.UseSharpRepository() but I don't need to dependecy inject a repository, I'll create those myself. But the config-based repository needs the dbcontext injected. I don't know how to accomplish that.

**Comment by GiganteX** [comment]
Omar, I made a very small demo project that shows the issue: 
https://github.com/GiganteX/CoreConsoleDemo
Could you take a look?

**Comment by omarpiani** [comment]
install Microsoft.Extensions.DependencyInjection
and then `var services = new ServiceCollection();`
add you services with ` services.UseSharpRepository()`
after that `var serviceProvider = services.BuildServiceProvider();`

now you can get Repository with  `var repo = serviceProvider.GetService<IRepository<Model,int>();`

**Comment by GiganteX** [comment]
(also SharpRepository.Ioc.Microsoft.DepebdencyInjection)
but I get null from serviceProvider.GetService<EmployeeRepository>(); ?

I would really like to be able to do new EmployeeRepository(config) ... As in my real code the repository is actually created that way in another assembly and it doesn't know about anything else than the ISharpRepositoryConfiguration that it has received earlier...

**Comment by omarpiani** [comment]
have you added the line `services.AddTransient<EmailRepository>(r => new EmailRepository(RepositoryFactory.BuildSharpRepositoryConfiguation(Configuration.GetSection("sharpRepository")), "efCore"));` I added in first reply?

if yes add in your "CoreConsoleDemo" a code failing!

**Comment by GiganteX** [comment]
I tried that, but `serviceProvider.GetService <EmployeeRepository>();` still returns null, I suppose because it doesn't know how to setuo the dbcontext. There is no options.UseSqlServer()...

**Comment by omarpiani** [comment]
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/ this package serves `UseSqlServer` extension

**Comment by GiganteX** [comment]
Yes but how do I setup the DependencyResolver to use that?

**Comment by omarpiani** [comment]
`services.AddDbContext<ContactContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")), ServiceLifetime.Transient);`

this line adds to dependency resolver the SqlServer dbcontext

**Comment by GiganteX** [comment]
Yes that works when I do it in a REST API project,... but not here.

I get this in the EmployeeRepository constructor:

SharpRepository.Repository.Ioc.RepositoryDependencyResolverException: 'Could not resolve type 'Microsoft.EntityFrameworkCore.DbContext' using the 'DependencyResolverWrapper'.

**Comment by omarpiani** [comment]
can you update your https://github.com/GiganteX/CoreConsoleDemo project with this code?

**Comment by GiganteX** [comment]
Sorry for late response. Yes, I have added it to the project now!

**Comment by omarpiani** [comment]
I created a pull request in your project for the changes you need, the main problem you have is that you put the AddDbContext after UseSharpRepository, order is important and DbContext must be declared before

**Comment by GiganteX** [comment]
I see... I had no idea about the order! :) Thanks a lot, Omar, it works now! :)
