### ISSUE TITLE
Does this work with Core 3? I am not having much luck.

### ISSUE THREAD

**Issue by VictorioBerra** [SharpRepository/SharpRepository#243]
My ServiceCollection never gets populated with any IRepositories. Before i start sharing code, im wondering does even work with the latest Core both EF Core and ASPNET Core?

**Comment by VictorioBerra** [comment]
Some more info, apparently, in aspnet core 3 you can no longer return IServiceProvider from ConfigureServices. So you will need to somehow allow us to register in program.cs during the hostbuilder setup via [`useserviceproviderfactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuilder.useserviceproviderfactory?view=aspnetcore-3.0)

Also, until now, I did not know using StructureMap's IOC [**method forces you to use StructureMap as your IoC container**](https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Ioc.Microsoft.DependencyInjection/ServicesCollectionExtensions.cs#L45). Am I understanding that correctly? That is not really an acceptible solution IMO... you should use the default core IoC implementation if possible.

**Comment by omarpiani** [comment]
Hi, I try to setup in a .NET Core MVC project and effectivelly dependency resolution has some problems... in general there is no problem with .NET Standard 2.0 libraries, for instance this guy https://github.com/SharpRepository/SharpRepository/issues/242

Why I use structuremap even in .net core is explained here: https://github.com/SharpRepository/SharpRepository/issues/191

**Comment by omarpiani** [comment]
https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/issues/47

You are ritght, we need to update something, probably is time to move to Lamar as suggested

**Comment by omarpiani** [comment]
I updated some things in order to get working a ASP.NET Core 3.0 project. 
I didn't found how to configure a new  ASP.NET Core 3.0 configured with a single row.

[This guide](https://github.com/SharpRepository/SharpRepository/wiki/Getting-started#aspnet-core-30-applications) helps you to setup a project with Autofac

Let me know if works!

**Comment by VictorioBerra** [comment]
Did you do the work in a branch or is this just on master?

**Comment by omarpiani** [comment]
it's merged today in develop

**Comment by VictorioBerra** [comment]
```
Version conflict detected for Microsoft.Extensions.DependencyInjection. Install/reference Microsoft.Extensions.DependencyInjection 3.0.0 directly to project MyApp to resolve this issue. 
 MyApp  -> Microsoft.EntityFrameworkCore.Sqlite 3.0.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 3.0.0 -> Microsoft.EntityFrameworkCore.Relational 3.0.0 -> Microsoft.EntityFrameworkCore 3.0.0 -> Microsoft.Extensions.DependencyInjection (>= 3.0.0) 
 MyApp  -> SharpRepository.Ioc.Microsoft.DependencyInjection 2.1.0-prerelease -> Microsoft.Extensions.DependencyInjection (>= 2.1.0 && < 3.0.0). 

```

![image](https://user-images.githubusercontent.com/2934507/67590324-5d6dc580-f720-11e9-87f1-29164f9f215d.png)

**Comment by omarpiani** [comment]
It's right, you dont need SharpRepository.Ioc.Microsoft.DependencyInjection, remove it

**Comment by VictorioBerra** [comment]
So how do I register my config and all that without that package?

**Comment by VictorioBerra** [comment]
Ohh you said to use AutoFac, I see.

**Comment by VictorioBerra** [comment]
Can you elaborate on why we need this:

```csharp
// Passes service provide to SharpRepository
RepositoryDependencyResolver.SetDependencyResolver(app.ApplicationServices);
```

**Comment by VictorioBerra** [comment]
```
ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ApplicationDbContext'.
```

Not sure what I am missing.

**Comment by omarpiani** [comment]
`RepositoryDependencyResolver.SetDependencyResolver(app.ApplicationServices);` because inside sharprepository I need to resolve DbContext or IMemoryCache or whatever

Seed in Main?  are you using EntityFrameworkCore? https://docs.microsoft.com/it-it/ef/core/modeling/data-seeding here's how

**Comment by VictorioBerra** [comment]
For the record I am using IdentityDbContext, so maybe that wont work???

**Comment by VictorioBerra** [comment]
Heres my startup:

Right now, if I click F5 on my web page, my app crashed with "object disposed" exception on my `public class ApplicationDbContext : IdentityDbContext`

```csharp
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Pumpkin.Beer.Taste.Data;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using AutoMapper;
using Microsoft.AspNetCore.HttpOverrides;
using Pumpkin.Beer.Taste.Services;
using Autofac;
using SharpRepository.Ioc.Autofac;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using SharpRepository.Repository.Ioc;

namespace Pumpkin.Beer.Taste
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options => { 
                options.UseMySql(Configuration.GetConnectionString("MySQLConnection"), mySqlOptions =>
                {                    
                    mySqlOptions.ServerVersion(new Version(5, 7), ServerType.MySql); // replace with your Server Version and Type
                });
            });

            services
                .AddDefaultIdentity<IdentityUser>(options => {
                    options.Password.RequireDigit = false;
                    options.Password.RequiredLength = 4;
                    options.Password.RequireLowercase = false;
                    options.Password.RequireNonAlphanumeric = false;
                    options.Password.RequireUppercase = false;
                    options.Password.RequiredUniqueChars = 0;
                })
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
            services
                .AddRazorPages()
                .AddRazorRuntimeCompilation();

            services.AddAutoMapper(typeof(Startup));

            services.AddTransient<IdentitySeed>();
            services.AddTransient<DataSeed>();
            services.AddSingleton<IClockService, ClockService>();

        }

        public void ConfigureContainer(ContainerBuilder builder)
        {
            builder.RegisterSharpRepository(Configuration.GetSection("sharpRepository"), "efCore"); // for Ef Core
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();

            app.UseRouting();

            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });

            // Passes service provide to SharpRepository
            // https://github.com/SharpRepository/SharpRepository/blob/develop/SharpRepository.Samples.Core3Mvc/Startup.cs
            RepositoryDependencyResolver.SetDependencyResolver(app.ApplicationServices);
        }
    }
}

```

**Comment by VictorioBerra** [comment]
Got it, I forgot to register as transient... why is this needed?

**Comment by omarpiani** [comment]
Trasient means that every time you resolve, container will instantiate a new object

**Comment by VictorioBerra** [comment]
Right, but default is scoped, why change it?

**Comment by omarpiani** [comment]
sorry for late reply.
Because it will avoid dbcontext disposed issues, obviously you risk to encouter the opposite problem when you are updating data connected from 2 different repositories.

**Comment by omarpiani** [comment]
I'm releasing as stable this .NET Core 3 compatible packages
