### ISSUE TITLE
AsNoTracking?

### ISSUE THREAD

**Issue by VictorioBerra** [SharpRepository/SharpRepository#244]
How do I set AsNoTracking when using a regular repo?

**Comment by omarpiani** [comment]
repo.AsQueryable().AsNoTracking()

**Comment by VictorioBerra** [comment]
And then how would you start using repo methods like FindAll? You cant chain anymore.

**Comment by omarpiani** [comment]
no, write an IRepository<> extension to get your particular linq ef specific query in a row.

 I have some memory of this, I will search later, maybe we can put AsNoTracking in specifications

**Comment by VictorioBerra** [comment]
Awsome thanks. I'd love to see an example of the extension too.

**Comment by omarpiani** [comment]
something like 

```
public IQueryable<Order> FindAllAsNoTracking(this IRepository<Order,int> repository, Func<Order, bool>  predicate) {
 return repo.AsQueryable().AsNoTracking().Where(predicate);
}
```
in a static class

**Comment by omarpiani** [comment]
I've added this as a new fetch strategy, go here for guide https://github.com/SharpRepository/SharpRepository/wiki/EF-AsNoTraking
