### ISSUE TITLE
.NET Core 3.1 DI/AutoFac version issue

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#248]
Hi guys, it's a me again, nagging about things... ;) 

So I was trying to do a .NET Core 3.1 app, and I followed the instructions at:
https://github.com/SharpRepository/SharpRepository/wiki/Getting-started
(under section "ASP.NET Core 3.0 Applications")

```
Install-Package Autofac.Extensions.DependencyInjection
Install-Package SharpRepository.Ioc.Autofac --Prerelease
```

But there are version conflicts:
Autofac.Extensions.DependencyInjection requires AutoFac >= 5.0.0
SharpRepository.Ioc.Autofac (version 2.1.0 pre) requires AutoFac < 5.0.0

So, yeah, that won't work.

I "solved" it by using older version 5.0.1 of Autofac.Extensions.DependencyInjection which uses AutoFac >= 4.9.1 ...
But then I have other packages that needs AutoFac >= 5.0.0.....

Sometimes development is too much juggling with package versions.... ;)

Oh, and that line "Install-Package SharpRepository.Ioc.Autofac --Prerelease" doesn't work by the way, not in my VS 2019 at least. This is the output I get:

```
PM> Install-Package SharpRepository.Ioc.Autofac --Prerelease
Install-Package : Project '--Prerelease' is not found.
At line:1 char:1
+ Install-Package SharpRepository.Ioc.Autofac --Prerelease
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (--Prerelease:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
```

But I could find it in the GUI and install it that way so no biggie for me, but I think its a good idea to update the documentation about that.

**Comment by omarpiani** [comment]
Hi! there's a brand new Aufofac 6 version.

You can install the previews 5 version or try to install with **-Force** to tell us if is working

**Comment by omarpiani** [comment]
btw I need nuget code from @jtreuting  in order to update packages

**Comment by omarpiani** [comment]
I released a new version of packages that supports Autofac 5 for 2.1

Let me know! if all its ok

**Comment by GiganteX** [comment]
Hey! Great! Sorry for slow response. I'll give it a try today!
