### ISSUE TITLE
MongoDBRepository is needed to update driver version.

### ISSUE THREAD

**Issue by GodSpeedXI** [SharpRepository/SharpRepository#249]
I'm new user in SharpRepository. I just create a simple .net framework project and install latest version of SharpRepository.

I found that MongoDb driver version 2.7 has a bug.

Method not found: 'DnsClient.IDnsQueryResponse DnsClient.LookupClient.Query(System.String, DnsClient.QueryType)'

I think it should be update to the new version.

**Comment by omarpiani** [comment]
Hello! I pushed right now package 2.1.1 with mongo driver 2.10.2

Btw seems I lost one commit. Really strange.
