### ISSUE TITLE
How to append item to the List<> of a record? [MongoDb]

### ISSUE THREAD

**Issue by GodSpeedXI** [SharpRepository/SharpRepository#250]
This is the entity I have created.
```
public class NOrder
{
        [BsonRepresentation(BsonType.ObjectId)]
        [BsonElement("_id")]
        public virtual string Id { get; set; }
        [BsonRequired]
        public string NOrderNo { get; set; }
        [BsonRequired] 
        public List<NOrderLog> NLogNotes { get; set; }
}
```
I want to add NOrderLog item to the  NLogNotes. so I create a method in the repository like this.

```
public void AddLogNoteByOrderNo(string orderNo, NOrderLog logNote)
{
     var orderRecord = this.Find(o => o.NOrderNo == orderNo);

      if (!(orderRecord is null))
      {
           orderRecord.NLogNotes.Add(logNote);
           Update(orderRecord);
       }
}
```
The problem is when the update occurred the array of the record is replaced by a new one. The older items are gone.

I need solution for this please.
Thank you.

**Comment by omarpiani** [comment]
Entity relationship in Mongo is a bit tricky, I suppose you want an embedded document, you need to know the normal MongoDriver behavior in this case. 

Probably you need this: https://github.com/dj-nitehawk/MongoDB.Entities let me know how it works. Can be a good addition to SharpRepository

**Comment by GodSpeedXI** [comment]
> Probably you need this: https://github.com/dj-nitehawk/MongoDB.Entities let me know how it works. Can be a good addition to SharpRepository

The library can solve my issue.
Thanks.
