### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by NdubuisiJr** [SharpRepository/SharpRepository#252]
Hello Team

I came across this repo and I'm very excited to have found it. But right now. I don't know how to use it. 
Can you create a quick 'getting started' session on the readme or if you have a documentation page, you could just share the link on the readme. 

Thanks

**Comment by omarpiani** [comment]
Hi, I don't understand.

Readme.md has link to getting-started 
![image](https://user-images.githubusercontent.com/2690653/113584254-f64d8380-962a-11eb-864e-960b903bb175.png)

that points to wiki:
https://github.com/SharpRepository/SharpRepository/wiki/Getting-started

**Comment by NdubuisiJr** [comment]
Hi, 
I was scheming too fast, I totally skipped it.

Thanks
