### ISSUE TITLE
SharpRepository.Ioc.Microsoft.DependencyInjection vs EF Core

### ISSUE THREAD

**Issue by GiganteX** [SharpRepository/SharpRepository#256]
Hi !

2.1.1 requires Microsoft.Extensions.DependencyInjection  >= 2.1.1 and < 3.0.0

And EntityFrameworkCore 5.0.8 (which I an using) requires Microsoft.Extensions.DependencyInjection 5.0.2

Can you update the package to work with the newer EFCore?

**Comment by omarpiani** [comment]
let me check tomorrow

**Comment by omarpiani** [comment]
try new package!

**Comment by GiganteX** [comment]
Great response-time! :)
Unfortunately, I'm getting: "Unable to find package SharpRepository >= 2.2.1"
Seems it's not available on nuget

**Comment by omarpiani** [comment]
ahh, forget there's a new Repository ready to ship, try now.

**Comment by GiganteX** [comment]
It builds properly! Leaving for a week, will do better testing once I'm back, but it sure seems to work at a glance! :)
Thanks!

**Comment by GiganteX** [comment]
Sorry, forgot to give the feedback!
It keeps working nicely for me, so I'm happy with this fix!
