### ISSUE TITLE
Autofac and InstancePerHttpRequest

### ISSUE THREAD

**Issue by jtreuting** [SharpRepository/SharpRepository#93]
Autofac needs the resolve request for anything that is InstancePerHttpRequest or InstancePerApiRequest to be done through the IDependencyResolver and not the IContainer as it is done now.

**Comment by omarpiani** [comment]
I studied and updated autofac and this problem.
Unfortunatelly nothing is changed in Autofac except the renaming from InstancePerHttpRequest or InstancePerApiRequest in InstancePerRequest.

I created a sample for Autofac with InstancePerRequest in https://github.com/SharpRepository/SharpRepository/tree/autofacMvcSample

The only solution is implement a different AutofacRepositoryDepencencyResolver.

We can do a full plugin that implements MVC5 + Autofac like I did for MVC5 and Core DependencyInjection + StructureMap, but after that why not for all permutations?

We need a different architectural way to choose different web framework and different ioc library to use.
