### ISSUE TITLE
Entity Framework Include methods

### ISSUE THREAD

**Issue by fiorebat** [SharpRepository/SharpRepository#99]
According to the following thread

https://groups.google.com/d/msgid/sharprepository/7656eeeb-9f2b-421e-8223-63dcf75116bf%40googlegroups.com

I'm requesting a better support for Include methods, used to force "eager loading" in Entity Framework.

Actually Find and FindAll methods use Including with

```
var specs = new Specification<Book>();
specs.FetchStrategy.Include(b => b.Author);
var books = repo.FindAll(specs);
```

`Get` and `GetAll` methods don't implement Import method.

MvcScaffolding repository template implements Including with `AllIncluding()` 

so `GetAllIncluding()` and `GetIncluding()` can be a good solution for our great repository +1

Can be implemented?

Thanks for all

**Comment by jtreuting** [comment]
This has _finally_ been implemented in the main branch.  New nuget packages should be released soon for this and other recent changes soon.
